# FLIPKART WEB SCRAPING THROUGH ALL/MULTIPLE PAGES

In [111]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

import warnings
warnings.filterwarnings("ignore")

import requests
from bs4 import BeautifulSoup
from urllib.request import urlopen, Request

url_list = []
for i in range(1,42):
     url = "https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"
     url_list.append(url)
    
def create_html_page(url):
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                      "AppleWebKit/537.36 (KHTML, like Gecko) "
                      "Chrome/136.0.0.0 Safari/537.36"
    }
    response = requests.get(url, headers=headers)

    # Check if request succeeded
    if response.status_code == 200:
        page_soup = BeautifulSoup(response.text, "html.parser")
        return page_soup
    else:
        print(f"Error: {response.status_code}")
        return None

In [112]:
url_list

['https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',
 'https://www.flipkart.com/search?q=mobile&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off']

In [113]:


def create_final_data(page_soup):
    data = {
        "ProductName": [],
        "Review&Ratings": [],
        "RatingNumber": [],
        "Memory": [],
        "Camera": [],
        "Processor": [],
        "Warranty": [],
        "Battery": [],
        "Sale & Actual Price": [],
        "Offer": []
    }
    all_info_class_name = "ZFwe0M row"
    containers = page_soup.find_all("div",{"class":all_info_class_name})
    for contain in containers:
        # Product name
        product_name = contain.find("div", {"class": "RG5Slk"})
        data["ProductName"].append(product_name.text if product_name else None)

        # Reviews & ratings
        rr = contain.find("span", {"class": "PvbNMB"})
        if rr:
            data["Review&Ratings"].append(rr.text)
            rating_tag = contain.find("div", {"class": "MKiFS6"})
            data["RatingNumber"].append(rating_tag.text if rating_tag else None)
        else:
            data["Review&Ratings"].append(None)
            data["RatingNumber"].append(None)

        # Specifications
        spec_list = contain.find("ul", {"class": "HwRTzP"})
        if spec_list:
            lis = spec_list.find_all("li")
            data["Memory"].append(lis[0].text if len(lis) > 0 else None)
            data["Camera"].append(lis[2].text if len(lis) > 2 else None)
            data["Processor"].append(lis[4].text if len(lis) > 4 else None)
            data["Warranty"].append(lis[5].text if len(lis) > 5 else None)
            data["Battery"].append(lis[3].text if len(lis) > 3 else None)
        else:
            data["Memory"].append(None)
            data["Camera"].append(None)
            data["Processor"].append(None)
            data["Warranty"].append(None)
            data["Battery"].append(None)

        # Price
        price = contain.find("div", {"class": "QiMO5r"})
        data["Sale & Actual Price"].append(price.text if price else None)

        # Offer
        offer_list = contain.find("div", {"class": "HQe8jr"})
        data["Offer"].append(offer_list.text if offer_list else "No Offer")

    # Build DataFrame after loop
    df = pd.DataFrame(data)
    print(df.head())

    return data

# MAIN SECTION

In [114]:
data_frame_list = []
for i,url in enumerate(url_list):
    print(f"Started url page {i+1}")
    page_soup = create_html_page(url_list[i])
    data_info = create_final_data(page_soup)
    data_frame_list.append(data_info)

Started url page 1
                           ProductName                  Review&Ratings  \
0  Tecno Spark Go 3 (Ink Black, 64 GB)        217 Ratings & 15 Reviews
1   IQOO Z11x 5G (Titan Black, 128 GB)      1,187 Ratings & 92 Reviews
2   vivo X200T (Seaside Lilac, 256 GB)   9,664 Ratings & 1,861 Reviews
3    POCO C85x 5G (Elite Black, 64 GB)     5,703 Ratings & 787 Reviews
4                        Kechaoda K115  43,777 Ratings & 2,753 Reviews

  RatingNumber                                         Memory  \
0          4.1                           4 GB RAM | 64 GB ROM
1          4.3                          6 GB RAM | 128 GB ROM
2          4.6                         12 GB RAM | 256 GB ROM
3          4.1    4 GB RAM | 64 GB ROM | Expandable Upto 2 TB
4          4.1  32 MB RAM | 32 MB ROM | Expandable Upto 32 GB

                                   Camera                  Processor  \
0     13MP Rear Camera | 8MP Front Camera            T7250 Processor
1                        50MP Rear Camera   12 Months Brand Warranty
2  50MP + 50MP + 50MP | 32MP Front Camera  Dimensity 9400+ Processor
3                        32MP Rear Camera            T8300 Processor
4          0.3MP + 0MP | 0MP Front Camera               NA Processor

                                            Warranty  \
0             1 Year Manufacturer Warranty for Phone
1                                                NaN
2  1 Year Warranty on Handset and 6 Months Warran...
3  1 Year Manufacturer Warranty for Phone and 6 M...
4                          3 Months Company Warranty

                                Battery    Sale & Actual Price    Offer
0      5000 mAh Lithium Polymer Battery  ₹12,499₹15,99921% off  21% off
1                      7200 mAh Battery   ₹27,671₹28,9994% off   4% off
2                      6200 mAh Battery  ₹59,999₹79,99925% off  25% off
3  6300 mAh Lithium-Ion Polymer Battery  ₹14,999₹20,99928% off  28% off
4                       850 mAh Battery    ₹1,099₹1,49926% off  26% off
Started url page 2
Error: 429

AttributeError: 'NoneType' object has no attribute 'find_all'

In [115]:
page_soup
data_info

{'ProductName': ['Tecno Spark Go 3 (Ink Black, 64 GB)',
  'IQOO Z11x 5G (Titan Black, 128 GB)',
  'vivo X200T (Seaside Lilac, 256 GB)',
  'POCO C85x 5G (Elite Black, 64 GB)',
  'Kechaoda K115',
  'BOLTT Evo (Lavender Bloom, 128 GB)',
  'BOLTT EVO (Berry Red, 64 GB)',
  'BOLTT EVO (Lavender Bloom, 64 GB)',
  'BOLTT EVO (Arctic White, 128 GB)',
  'vivo X200T (Stellar Black, 256 GB)',
  'Nokia 105 Classic Single Sim Keypad Phone, Without Charger',
  'Samsung Galaxy F07 (Green, 64 GB)',
  'IQOO Z11x 5G (Prismatic Green, 128 GB)',
  'POCO C85x 5G (Elite Black, 128 GB)',
  'IQOO Z11x 5G (Prismatic Green, 128 GB)',
  'PHILIPS E2101C',
  'Ai+ Pulse 2 (Purple, 64 GB)',
  'IQOO Z11x 5G (Titan Black, 256 GB)',
  'BOLTT EVO (Sky Blue, 64 GB)',
  'ringme R1+ JUMBO',
  'vivo X200T (Stellar Black, 512 GB)',
  'Kechaoda A27',
  'HMD 105 Dual Sim Keypad Phone with Built-in UPI App, Wireless FM Radio',
  'oneme FM-1 POWER 17C'],
 'Review&Ratings': ['217 Ratings\xa0&\xa015 Reviews',
  '1,187 Ratings\xa0&\xa092 Reviews',
  '9,664 Ratings\xa0&\xa01,861 Reviews',
  '5,703 Ratings\xa0&\xa0787 Reviews',
  '43,777 Ratings\xa0&\xa02,753 Reviews',
  '1,323 Ratings\xa0&\xa0638 Reviews',
  '894 Ratings\xa0&\xa0520 Reviews',
  '894 Ratings\xa0&\xa0520 Reviews',
  '1,323 Ratings\xa0&\xa0638 Reviews',
  '9,664 Ratings\xa0&\xa01,861 Reviews',
  '29,879 Ratings\xa0&\xa01,555 Reviews',
  '10,731 Ratings\xa0&\xa0767 Reviews',
  '1,187 Ratings\xa0&\xa092 Reviews',
  '5,703 Ratings\xa0&\xa0787 Reviews',
  '1,571 Ratings\xa0&\xa0121 Reviews',
  '75 Ratings\xa0&\xa012 Reviews',
  '12,967 Ratings\xa0&\xa0914 Reviews',
  '1,571 Ratings\xa0&\xa0121 Reviews',
  '894 Ratings\xa0&\xa0520 Reviews',
  '800 Ratings\xa0&\xa062 Reviews',
  '9,664 Ratings\xa0&\xa01,861 Reviews',
  '17,256 Ratings\xa0&\xa0938 Reviews',
  '6,692 Ratings\xa0&\xa0575 Reviews',
  '4 Ratings\xa0&\xa01 Reviews'],
 'RatingNumber': ['4.1',
  '4.3',
  '4.6',
  '4.1',
  '4.1',
  '4',
  '4.4',
  '4.4',
  '4',
  '4.6',
  '4',
  '4.2',
  '4.3',
  '4.1',
  '4.3',
  '3.7',
  '4.1',
  '4.3',
  '4.4',
  '4.1',
  '4.6',
  '4',
  '3.9',
  '4.8'],
 'Memory': ['4 GB RAM | 64 GB ROM',
  '6 GB RAM | 128 GB ROM',
  '12 GB RAM | 256 GB ROM',
  '4 GB RAM | 64 GB ROM | Expandable Upto 2 TB',
  '32 MB RAM | 32 MB ROM | Expandable Upto 32 GB',
  '6 GB RAM | 128 GB ROM | Expandable Upto 1 TB',
  '4 GB RAM | 64 GB ROM | Expandable Upto 1 TB',
  '4 GB RAM | 64 GB ROM | Expandable Upto 1 TB',
  '6 GB RAM | 128 GB ROM | Expandable Upto 1 TB',
  '12 GB RAM | 256 GB ROM',
  '32 MB RAM | 32 MB ROM',
  '4 GB RAM | 64 GB ROM | Expandable Upto 2 TB',
  '6 GB RAM | 128 GB ROM',
  '4 GB RAM | 128 GB ROM | Expandable Upto 2 TB',
  '8 GB RAM | 128 GB ROM',
  '32 MB RAM | 32 MB ROM',
  '4 GB RAM | 64 GB ROM | Expandable Upto 1 TB',
  '8 GB RAM | 256 GB ROM',
  '4 GB RAM | 64 GB ROM | Expandable Upto 1 TB',
  '32 MB RAM | 32 MB ROM',
  '12 GB RAM | 512 GB ROM',
  '32 MB RAM | 32 MB ROM | Expandable Upto 16 GB',
  '4 MB RAM | 4 MB ROM | Expandable Upto 32 GB',
  '32 MB RAM | 32 MB ROM'],
 'Camera': ['13MP Rear Camera | 8MP Front Camera',
  '50MP Rear Camera',
  '50MP + 50MP + 50MP | 32MP Front Camera',
  '32MP Rear Camera',
  '0.3MP + 0MP | 0MP Front Camera',
  '50MP + 2MP | 8MP Front Camera',
  '50MP + 2MP | 8MP Front Camera',
  '50MP + 2MP | 8MP Front Camera',
  '50MP + 2MP | 8MP Front Camera',
  '50MP + 50MP + 50MP | 32MP Front Camera',
  '0MP Front Camera',
  '50MP + 2MP | 8MP Front Camera',
  '50MP Rear Camera',
  '32MP Rear Camera',
  '50MP Rear Camera',
  '0.3MP Rear Camera',
  '50MP Rear Camera | 8MP Front Camera',
  '50MP Rear Camera',
  '50MP + 2MP | 8MP Front Camera',
  '1MP Rear Camera',
  '50MP + 50MP + 50MP | 32MP Front Camera',
  '0MP | 0MP Front Camera',
  '1000 mAh Battery',
  '0.3MP Rear Camera'],
 'Processor': ['T7250 Processor',
  '12 Months Brand Warranty',
  'Dimensity 9400+ Processor',
  'T8300 Processor',
  'NA Processor',
  'T7250 Processor',
  'T7250 Processor',
  'T7250 Processor',
  'T7250 Processor',
  'Dimensity 9400+ Processor',
  'SC6531E Processor',
  'Helio G99 Processor',
  '12 Months Brand Warranty',
  'T8300 Processor',
  '12 Months Brand Warranty',
  '1 Year',
  'T7250 Processor',
  '12 Months Brand Warranty',
  'T7250 Processor',
  '3 Months Manufacturer Defect Warranty',
  'Dimensity 9400+ Processor',
  'NA Processor',
  '1 Year Replacement.',
  '6 MONTHS WARRENTY'],
 'Warranty': ['1 Year Manufacturer Warranty for Phone',
  None,
  '1 Year Warranty on Handset and 6 Months Warranty on Accessories',
  '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories',
  '3 Months Company Warranty',
  "6.79'' HD+ punch hole display",
  "6.79'' HD+ punch hole display",
  "6.79'' HD+ punch hole display",
  "6.79'' HD+ punch hole display",
  '1 Year Warranty on Handset and 6 Months Warranty on Accessories',
  '1 Month Company Domestic Warranty by Company Authorized Service Center.',
  '1 Year Manufacturer Warranty for Device and 6 Months for In-Box Accessories',
  None,
  '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories',
  None,
  None,
  '1 Year Warranty on Handset and 6 Months Warranty on the Inbox Accessories',
  None,
  "6.79'' HD+ punch hole display",
  None,
  '1 Year Warranty on Handset and 6 Months Warranty on Accessories',
  '3 Months Company Warranty',
  None,
  None],
 'Battery': ['5000 mAh Lithium Polymer Battery',
  '7200 mAh Battery',
  '6200 mAh Battery',
  '6300 mAh Lithium-Ion Polymer Battery',
  '850 mAh Battery',
  '6000 mAh Lithium ion Battery',
  '6000 mAh Lithium ion Battery',
  '6000 mAh Lithium ion Battery',
  '6000 mAh Lithium ion Battery',
  '6200 mAh Battery',
  '800 mAh Battery',
  '5000 mAh Battery',
  '7200 mAh Battery',
  '6300 mAh Lithium-Ion Polymer Battery',
  '7200 mAh Battery',
  '1000 mAh Battery',
  '6000 mAh Battery',
  '7200 mAh Battery',
  '6000 mAh Lithium ion Battery',
  '4000 mAh Battery',
  '6200 mAh Battery',
  '800 mAh Battery',
  'SC6531E Processor',
  '3000 mAh Battery'],
 'Sale & Actual Price': ['₹12,499₹15,99921% off',
  '₹27,671₹28,9994% off',
  '₹59,999₹79,99925% off',
  '₹14,999₹20,99928% off',
  '₹1,099₹1,49926% off',
  '₹11,499₹18,99939% off',
  '₹9,999₹17,99944% off',
  '₹9,999₹17,99944% off',
  '₹11,499₹18,99939% off',
  '₹59,999₹80,00025% off',
  '₹1,069₹1,34920% off',
  '₹11,999',
  '₹27,277₹28,9995% off',
  '₹15,999₹21,99927% off',
  '₹28,849₹30,9996% off',
  '₹1,017₹1,29921% off',
  '₹10,999',
  '₹33,882₹39,99915% off',
  '₹9,999₹17,99944% off',
  '₹1,680₹2,49932% off',
  '₹69,999₹87,99920% off',
  '₹978₹1,49934% off',
  '₹1,079₹1,49928% off',
  '₹1,050₹1,99947% off'],
 'Offer': ['21% off',
  '4% off',
  '25% off',
  '28% off',
  '26% off',
  '39% off',
  '44% off',
  '44% off',
  '39% off',
  '25% off',
  '20% off',
  'No Offer',
  '5% off',
  '27% off',
  '6% off',
  '21% off',
  'No Offer',
  '15% off',
  '44% off',
  '32% off',
  '20% off',
  '34% off',
  '28% off',
  '47% off']}

In [116]:
pd.DataFrame(data_info)

,ProductName,Review&Ratings,RatingNumber,Memory,Camera,Processor,Warranty,Battery,Sale & Actual Price,Offer
0,"Tecno Spark Go 3 (Ink Black, 64 GB)",217 Ratings & 15 Reviews,4.1,4 GB RAM | 64 GB ROM,13MP Rear Camera | 8MP Front Camera,T7250 Processor,1 Year Manufacturer Warranty for Phone,5000 mAh Lithium Polymer Battery,"₹12,499₹15,99921% off",21% off
1,"IQOO Z11x 5G (Titan Black, 128 GB)","1,187 Ratings & 92 Reviews",4.3,6 GB RAM | 128 GB ROM,50MP Rear Camera,12 Months Brand Warranty,NaN,7200 mAh Battery,"₹27,671₹28,9994% off",4% off
2,"vivo X200T (Seaside Lilac, 256 GB)","9,664 Ratings & 1,861 Reviews",4.6,12 GB RAM | 256 GB ROM,50MP + 50MP + 50MP | 32MP Front Camera,Dimensity 9400+ Processor,1 Year Warranty on Handset and 6 Months Warran...,6200 mAh Battery,"₹59,999₹79,99925% off",25% off
3,"POCO C85x 5G (Elite Black, 64 GB)","5,703 Ratings & 787 Reviews",4.1,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,32MP Rear Camera,T8300 Processor,1 Year Manufacturer Warranty for Phone and 6 M...,6300 mAh Lithium-Ion Polymer Battery,"₹14,999₹20,99928% off",28% off
4,Kechaoda K115,"43,777 Ratings & 2,753 Reviews",4.1,32 MB RAM | 32 MB ROM | Expandable Upto 32 GB,0.3MP + 0MP | 0MP Front Camera,NA Processor,3 Months Company Warranty,850 mAh Battery,"₹1,099₹1,49926% off",26% off
5,"BOLTT Evo (Lavender Bloom, 128 GB)","1,323 Ratings & 638 Reviews",4,6 GB RAM | 128 GB ROM | Expandable Upto 1 TB,50MP + 2MP | 8MP Front Camera,T7250 Processor,6.79'' HD+ punch hole display,6000 mAh Lithium ion Battery,"₹11,499₹18,99939% off",39% off
6,"BOLTT EVO (Berry Red, 64 GB)",894 Ratings & 520 Reviews,4.4,4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,50MP + 2MP | 8MP Front Camera,T7250 Processor,6.79'' HD+ punch hole display,6000 mAh Lithium ion Battery,"₹9,999₹17,99944% off",44% off
7,"BOLTT EVO (Lavender Bloom, 64 GB)",894 Ratings & 520 Reviews,4.4,4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,50MP + 2MP | 8MP Front Camera,T7250 Processor,6.79'' HD+ punch hole display,6000 mAh Lithium ion Battery,"₹9,999₹17,99944% off",44% off
8,"BOLTT EVO (Arctic White, 128 GB)","1,323 Ratings & 638 Reviews",4,6 GB RAM | 128 GB ROM | Expandable Upto 1 TB,50MP + 2MP | 8MP Front Camera,T7250 Processor,6.79'' HD+ punch hole display,6000 mAh Lithium ion Battery,"₹11,499₹18,99939% off",39% off
9,"vivo X200T (Stellar Black, 256 GB)","9,664 Ratings & 1,861 Reviews",4.6,12 GB RAM | 256 GB ROM,50MP + 50MP + 50MP | 32MP Front Camera,Dimensity 9400+ Processor,1 Year Warranty on Handset and 6 Months Warran...,6200 mAh Battery,"₹59,999₹80,00025% off",25% off
10,"Nokia 105 Classic Single Sim Keypad Phone, Wit...","29,879 Ratings & 1,555 Reviews",4,32 MB RAM | 32 MB ROM,0MP Front Camera,SC6531E Processor,1 Month Company Domestic Warranty by Company A...,800 mAh Battery,"₹1,069₹1,34920% off",20% off
11,"Samsung Galaxy F07 (Green, 64 GB)","10,731 Ratings & 767 Reviews",4.2,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,50MP + 2MP | 8MP Front Camera,Helio G99 Processor,1 Year Manufacturer Warranty for Device and 6 ...,5000 mAh Battery,"₹11,999",No Offer
12,"IQOO Z11x 5G (Prismatic Green, 128 GB)","1,187 Ratings & 92 Reviews",4.3,6 GB RAM | 128 GB ROM,50MP Rear Camera,12 Months Brand Warranty,NaN,7200 mAh Battery,"₹27,277₹28,9995% off",5% off
13,"POCO C85x 5G (Elite Black, 128 GB)","5,703 Ratings & 787 Reviews",4.1,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,32MP Rear Camera,T8300 Processor,1 Year Manufacturer Warranty for Phone and 6 M...,6300 mAh Lithium-Ion Polymer Battery,"₹15,999₹21,99927% off",27% off
14,"IQOO Z11x 5G (Prismatic Green, 128 GB)","1,571 Ratings & 121 Reviews",4.3,8 GB RAM | 128 GB ROM,50MP Rear Camera,12 Months Brand Warranty,NaN,7200 mAh Battery,"₹28,849₹30,9996% off",6% off
15,PHILIPS E2101C,75 Ratings & 12 Reviews,3.7,32 MB RAM | 32 MB ROM,0.3MP Rear Camera,1 Year,NaN,1000 mAh Battery,"₹1,017₹1,29921% off",21% off
16,"Ai+ Pulse 2 (Purple, 64 GB)","12,967 Ratings & 914 Reviews",4.1,4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,50MP Rear Camera | 8MP Front Camera,T7250 Processor,1 Year Warranty on Handset and 6 Months Warran...,6000 mAh Battery,"₹10,999",No Offer
17,"IQOO Z11x 5G (Titan Black, 256 GB)","1,571 Ratings & 121 Reviews",4.3,8 GB RAM | 256 GB ROM,50MP Rear Camera,12 Months Brand Warranty,NaN,7200 mAh Battery,"₹33,882₹39,99915% off",15% off
18,"BOLTT EVO (Sky Blue, 64 GB)",894 Ratings & 520 Reviews,4.4,4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,50MP + 2MP | 8MP Front Camera,T7250 Processor,6.79'' HD+ punch hole display,6000 mAh Lithium ion Battery,"₹9,999₹17,99944% off",44% off
19,ringme R1+ JUMBO,800 Ratings & 62 Reviews,4.1,32 MB RAM | 32 MB ROM,1MP Rear Camera,3 Months Manufacturer Defect Warranty,NaN,4000 mAh Battery,"₹1,680₹2,49932% off",32% off
20,"vivo X200T (Stellar Black, 512 GB)","9,664 Ratings & 1,861 Reviews",4.6,12 GB RAM | 512 GB ROM,50MP + 50MP + 50MP | 32MP Front Camera,Dimensity 9400+ Processor,1 Year Warranty on Handset and 6 Months Warran...,6200 mAh Battery,"₹69,999₹87,99920% off",20% off
21,Kechaoda A27,"17,256 Ratings & 938 Reviews",4,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB,0MP | 0MP Front Camera,NA Processor,3 Months Company Warranty,800 mAh Battery,"₹978₹1,49934% off",34% off
22,HMD 105 Dual Sim Keypad Phone with Built-in UP...,"6,692 Ratings & 575 Reviews",3.9,4 MB RAM | 4 MB ROM | Expandable Upto 32 GB,1000 mAh Battery,1 Year Replacement.,NaN,SC6531E Processor,"₹1,079₹1,49928% off",28% off
23,oneme FM-1 POWER 17C,4 Ratings & 1 Reviews,4.8,32 MB RAM | 32 MB ROM,0.3MP Rear Camera,6 MONTHS WARRENTY,NaN,3000 mAh Battery,"₹1,050₹1,99947% off",47% off

In [117]:
len(data_frame_list)

1

In [118]:
df_all = []
for i in range(len(data_frame_list)):
    df = pd.DataFrame(data_frame_list[i])
    df_all.append(df)

In [119]:
final_df = pd.concat(df_all, ignore_index=True)

In [120]:
final_df["ProductName"].unique().shape

(23,)

In [121]:
final_df["ProductName"].unique()

<ArrowStringArray>
[                                   'Tecno Spark Go 3 (Ink Black, 64 GB)',
                                     'IQOO Z11x 5G (Titan Black, 128 GB)',
                                     'vivo X200T (Seaside Lilac, 256 GB)',
                                      'POCO C85x 5G (Elite Black, 64 GB)',
                                                          'Kechaoda K115',
                                     'BOLTT Evo (Lavender Bloom, 128 GB)',
                                           'BOLTT EVO (Berry Red, 64 GB)',
                                      'BOLTT EVO (Lavender Bloom, 64 GB)',
                                       'BOLTT EVO (Arctic White, 128 GB)',
                                     'vivo X200T (Stellar Black, 256 GB)',
             'Nokia 105 Classic Single Sim Keypad Phone, Without Charger',
                                      'Samsung Galaxy F07 (Green, 64 GB)',
                                 'IQOO Z11x 5G (Prismatic Green, 128 GB)',
                                     'POCO C85x 5G (Elite Black, 128 GB)',
                                                         'PHILIPS E2101C',
                                            'Ai+ Pulse 2 (Purple, 64 GB)',
                                     'IQOO Z11x 5G (Titan Black, 256 GB)',
                                            'BOLTT EVO (Sky Blue, 64 GB)',
                                                       'ringme R1+ JUMBO',
                                     'vivo X200T (Stellar Black, 512 GB)',
                                                           'Kechaoda A27',
 'HMD 105 Dual Sim Keypad Phone with Built-in UPI App, Wireless FM Radio',
                                                   'oneme FM-1 POWER 17C']
Length: 23, dtype: str

In [122]:
final_df.shape

(24, 10)

In [123]:
final_df.drop_duplicates()

,ProductName,Review&Ratings,RatingNumber,Memory,Camera,Processor,Warranty,Battery,Sale & Actual Price,Offer
0,"Tecno Spark Go 3 (Ink Black, 64 GB)",217 Ratings & 15 Reviews,4.1,4 GB RAM | 64 GB ROM,13MP Rear Camera | 8MP Front Camera,T7250 Processor,1 Year Manufacturer Warranty for Phone,5000 mAh Lithium Polymer Battery,"₹12,499₹15,99921% off",21% off
1,"IQOO Z11x 5G (Titan Black, 128 GB)","1,187 Ratings & 92 Reviews",4.3,6 GB RAM | 128 GB ROM,50MP Rear Camera,12 Months Brand Warranty,NaN,7200 mAh Battery,"₹27,671₹28,9994% off",4% off
2,"vivo X200T (Seaside Lilac, 256 GB)","9,664 Ratings & 1,861 Reviews",4.6,12 GB RAM | 256 GB ROM,50MP + 50MP + 50MP | 32MP Front Camera,Dimensity 9400+ Processor,1 Year Warranty on Handset and 6 Months Warran...,6200 mAh Battery,"₹59,999₹79,99925% off",25% off
3,"POCO C85x 5G (Elite Black, 64 GB)","5,703 Ratings & 787 Reviews",4.1,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,32MP Rear Camera,T8300 Processor,1 Year Manufacturer Warranty for Phone and 6 M...,6300 mAh Lithium-Ion Polymer Battery,"₹14,999₹20,99928% off",28% off
4,Kechaoda K115,"43,777 Ratings & 2,753 Reviews",4.1,32 MB RAM | 32 MB ROM | Expandable Upto 32 GB,0.3MP + 0MP | 0MP Front Camera,NA Processor,3 Months Company Warranty,850 mAh Battery,"₹1,099₹1,49926% off",26% off
5,"BOLTT Evo (Lavender Bloom, 128 GB)","1,323 Ratings & 638 Reviews",4,6 GB RAM | 128 GB ROM | Expandable Upto 1 TB,50MP + 2MP | 8MP Front Camera,T7250 Processor,6.79'' HD+ punch hole display,6000 mAh Lithium ion Battery,"₹11,499₹18,99939% off",39% off
6,"BOLTT EVO (Berry Red, 64 GB)",894 Ratings & 520 Reviews,4.4,4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,50MP + 2MP | 8MP Front Camera,T7250 Processor,6.79'' HD+ punch hole display,6000 mAh Lithium ion Battery,"₹9,999₹17,99944% off",44% off
7,"BOLTT EVO (Lavender Bloom, 64 GB)",894 Ratings & 520 Reviews,4.4,4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,50MP + 2MP | 8MP Front Camera,T7250 Processor,6.79'' HD+ punch hole display,6000 mAh Lithium ion Battery,"₹9,999₹17,99944% off",44% off
8,"BOLTT EVO (Arctic White, 128 GB)","1,323 Ratings & 638 Reviews",4,6 GB RAM | 128 GB ROM | Expandable Upto 1 TB,50MP + 2MP | 8MP Front Camera,T7250 Processor,6.79'' HD+ punch hole display,6000 mAh Lithium ion Battery,"₹11,499₹18,99939% off",39% off
9,"vivo X200T (Stellar Black, 256 GB)","9,664 Ratings & 1,861 Reviews",4.6,12 GB RAM | 256 GB ROM,50MP + 50MP + 50MP | 32MP Front Camera,Dimensity 9400+ Processor,1 Year Warranty on Handset and 6 Months Warran...,6200 mAh Battery,"₹59,999₹80,00025% off",25% off
10,"Nokia 105 Classic Single Sim Keypad Phone, Wit...","29,879 Ratings & 1,555 Reviews",4,32 MB RAM | 32 MB ROM,0MP Front Camera,SC6531E Processor,1 Month Company Domestic Warranty by Company A...,800 mAh Battery,"₹1,069₹1,34920% off",20% off
11,"Samsung Galaxy F07 (Green, 64 GB)","10,731 Ratings & 767 Reviews",4.2,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,50MP + 2MP | 8MP Front Camera,Helio G99 Processor,1 Year Manufacturer Warranty for Device and 6 ...,5000 mAh Battery,"₹11,999",No Offer
12,"IQOO Z11x 5G (Prismatic Green, 128 GB)","1,187 Ratings & 92 Reviews",4.3,6 GB RAM | 128 GB ROM,50MP Rear Camera,12 Months Brand Warranty,NaN,7200 mAh Battery,"₹27,277₹28,9995% off",5% off
13,"POCO C85x 5G (Elite Black, 128 GB)","5,703 Ratings & 787 Reviews",4.1,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,32MP Rear Camera,T8300 Processor,1 Year Manufacturer Warranty for Phone and 6 M...,6300 mAh Lithium-Ion Polymer Battery,"₹15,999₹21,99927% off",27% off
14,"IQOO Z11x 5G (Prismatic Green, 128 GB)","1,571 Ratings & 121 Reviews",4.3,8 GB RAM | 128 GB ROM,50MP Rear Camera,12 Months Brand Warranty,NaN,7200 mAh Battery,"₹28,849₹30,9996% off",6% off
15,PHILIPS E2101C,75 Ratings & 12 Reviews,3.7,32 MB RAM | 32 MB ROM,0.3MP Rear Camera,1 Year,NaN,1000 mAh Battery,"₹1,017₹1,29921% off",21% off
16,"Ai+ Pulse 2 (Purple, 64 GB)","12,967 Ratings & 914 Reviews",4.1,4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,50MP Rear Camera | 8MP Front Camera,T7250 Processor,1 Year Warranty on Handset and 6 Months Warran...,6000 mAh Battery,"₹10,999",No Offer
17,"IQOO Z11x 5G (Titan Black, 256 GB)","1,571 Ratings & 121 Reviews",4.3,8 GB RAM | 256 GB ROM,50MP Rear Camera,12 Months Brand Warranty,NaN,7200 mAh Battery,"₹33,882₹39,99915% off",15% off
18,"BOLTT EVO (Sky Blue, 64 GB)",894 Ratings & 520 Reviews,4.4,4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,50MP + 2MP | 8MP Front Camera,T7250 Processor,6.79'' HD+ punch hole display,6000 mAh Lithium ion Battery,"₹9,999₹17,99944% off",44% off
19,ringme R1+ JUMBO,800 Ratings & 62 Reviews,4.1,32 MB RAM | 32 MB ROM,1MP Rear Camera,3 Months Manufacturer Defect Warranty,NaN,4000 mAh Battery,"₹1,680₹2,49932% off",32% off
20,"vivo X200T (Stellar Black, 512 GB)","9,664 Ratings & 1,861 Reviews",4.6,12 GB RAM | 512 GB ROM,50MP + 50MP + 50MP | 32MP Front Camera,Dimensity 9400+ Processor,1 Year Warranty on Handset and 6 Months Warran...,6200 mAh Battery,"₹69,999₹87,99920% off",20% off
21,Kechaoda A27,"17,256 Ratings & 938 Reviews",4,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB,0MP | 0MP Front Camera,NA Processor,3 Months Company Warranty,800 mAh Battery,"₹978₹1,49934% off",34% off
22,HMD 105 Dual Sim Keypad Phone with Built-in UP...,"6,692 Ratings & 575 Reviews",3.9,4 MB RAM | 4 MB ROM | Expandable Upto 32 GB,1000 mAh Battery,1 Year Replacement.,NaN,SC6531E Processor,"₹1,079₹1,49928% off",28% off
23,oneme FM-1 POWER 17C,4 Ratings & 1 Reviews,4.8,32 MB RAM | 32 MB ROM,0.3MP Rear Camera,6 MONTHS WARRENTY,NaN,3000 mAh Battery,"₹1,050₹1,99947% off",47% off

In [124]:
final_df.to_csv("flipkart_mobile_phones.csv")