In [1]:
from bs4 import BeautifulSoup
import requests

In [2]:
headers = {
     "User-Agent": "Mozilla/5.0 (AppleWebKit/537.36; Chrome/136.0.0.0; Safari/537.36) MyScraperBot/1.0 (contact: muskaan19830@gmail.com)"
}

In [3]:
url = "https://en.wikipedia.org/wiki/List_of_largest_companies_in_India"
page = requests.get(url, headers=headers)
soup = BeautifulSoup(page.text,'html')

In [4]:
print(soup)

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>List of largest companies in India - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-thumbsize-clientpref-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"d6e494f6-5255-4e35-91db-9e7c5698481e","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_largest_companies_in_India","wgTitle":"List of largest companies in India","wgCurRevisionId":1354790507,"wgRevisionId":1354790507,"wgArticleId":61418237,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Lists of largest private companies by country","Lists of companies of India","Companies of India","Economy of India lists"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_largest_companies_in_India","wgRelevantArticleId":61418237,"wgTempUserName":null,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}},"namespaces":[0,4]},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditForceShowCaptcha":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgMediaViewerMobileBeta":false,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":20000,"wgParsoidHtmlVersion":"2.8.0","parsermigration-parsoid":true,"wgPageAssessments":{"Companies":{"class":"List","importance":"Low"},"India":{"class":"List","importance":"Low"},"Lists":{"class":"List","importance":"Low"},"Project-independent assessment":{"class":"List","importance":""}},"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[]},"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgULSLanguageSelectorV2Enabled":true,"wgWikibaseItemId":"Q66087467","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"wgPersonalDashboardMenuVisible":false};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.parsoid.styles":"ready","ext.cite.styles":"ready","mediawiki.skinning.content.parsoid":"ready","ext.wikimediamessages.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","ext.parsermigration.reportbug.init","site","mediawiki.page.ready","jquery.tablesorter","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","ext.testKitchen","ext.wikimediaCustomizations.donorAccountCreation","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});mw.user.options.set({"usecodemirror":1});
}];});});</script>
<link href="/w/load.php?lang=en&amp;modules=ext.cite.parsoid.styles%7Cext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cjquery.tablesorter.styles%7Cmediawiki.skinning.content.parsoid%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<meta content="MediaWiki 1.47.0-wmf.20" name="generator"/>
<meta content="origin" name="referrer"/>
<meta content="origin-when-cross-origin" name="referrer"/>
<meta content="max-image-preview:standard" name="robots"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="width=1120" name="viewport"/>
<meta content="List of largest companies in India - Wikipedia" property="og:title"/>
<meta content="website" property="og:type"/>
<link href="//thumb.wikimedia.org" rel="preconnect"/>
<link href="/w/index.php?title=List_of_largest_companies_in_India&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
<link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
<link href="/static/favicon/wikipedia.ico" rel="icon"/>
<link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
<link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="https://en.wikipedia.org/wiki/List_of_largest_companies_in_India" rel="canonical"/>
<link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
<link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
<link href="//meta.wikimedia.org" rel="dns-prefetch"/>
<link href="auth.wikimedia.org" rel="dns-prefetch"/>
</head>
<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-List_of_largest_companies_in_India rootpage-List_of_largest_companies_in_India skin-vector-2022 action-view">
<div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region"></div><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
<header class="vector-header mw-header no-font-mode-scale">
<div class="vector-header-start">
<nav aria-label="Site" class="vector-main-menu-landmark">
<div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
<input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu cdx-button__icon"></span>
<span class="vector-dropdown-label-text">Main menu</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
<div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
<div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
<div class="vector-pinnable-header-label">Main menu</div>
<button aria-label="Move Main menu to sidebar" class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
<button aria-label="Hide Main menu" class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>
<div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
<div class="vector-menu-heading">
		Navigation
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a></li><li class="mw-list-item" id="n-contents"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a></li><li class="mw-list-item" id="n-aboutsite"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li class="mw-list-item" id="n-contactpage"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
<div class="vector-menu-heading">
		Contribute
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-help"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li class="mw-list-item" id="n-introduction"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]"><span>Recent changes</span></a></li><li class="mw-list-item" id="n-upload"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li class="mw-list-item" id="n-specialpages"><a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]"><span>Special pages</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<a class="mw-logo" href="/wiki/Main_Page">
<img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
<span class="mw-logo-container skin-invert">
<img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
<img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
</span>
</a>
</div>
<div class="vector-header-end">
<div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
<a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search cdx-button__icon"></span>
<span>Search</span>
</a>
<div class="vector-typeahead-search-container">
<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
<form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
<div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
<div class="cdx-text-input cdx-text-input--has-start-icon">
<input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>
<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
</div>
<input name="title" type="hidden" value="Special:Search"/>
</div>
<button class="cdx-button cdx-search-input__end-button">Search</button>
</form>
</div>
</div>
</div>
<nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
<div class="vector-user-links-main">
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<nav aria-label="Appearance" class="vector-appearance-landmark">
<div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
<input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label"><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance cdx-button__icon"></span>
<span class="vector-dropdown-label-text">Appearance</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
</div>
</div>
</div>
</nav>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item vector-menu-item--collapsible" id="pt-sitesupport-2"><a class="" data-mw-donate-attempt="top_link" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a>
</li>
<li class="mw-list-item vector-menu-item--collapsible" id="pt-createaccount-2"><a class="" data-mw-interface="" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+companies+in+India" title="You are encouraged to create an account and log in; however, it is not mandatory"><span>Create account</span></a>
</li>
<li class="mw-list-item vector-menu-item--collapsible" id="pt-login-2"><a accesskey="o" class="" data-mw-interface="" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+largest+companies+in+India" title="You're encouraged to log in; however, it's not mandatory. [o]"><span>Log in</span></a>
</li>
</ul>
</div>
</div>
</div>
<div class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out vector-user-links-dropdown--collapsible" id="vector-user-links-dropdown" title="Log in and more options">
<input aria-haspopup="true" aria-label="Personal tools" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-user-links-dropdown" id="vector-user-links-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-user-links-dropdown-checkbox" id="vector-user-links-dropdown-label"><span class="vector-icon mw-ui-icon-userAvatar mw-ui-icon-wikimedia-userAvatar cdx-button__icon"></span>
<span class="vector-dropdown-label-text">Personal tools</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-menu mw-portlet mw-portlet-personal" id="p-personal" title="User menu">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item vector-menu-item--collapsible" id="pt-sitesupport"><a class="" data-mw-donate-attempt="top_link" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span class="vector-icon mw-ui-icon-heart mw-ui-icon-wikimedia-heart cdx-button__icon"></span>
<span>Donate</span></a>
</li>
<li class="mw-list-item vector-menu-item--collapsible" id="pt-createaccount"><a class="" data-mw-interface="" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+companies+in+India" title="You are encouraged to create an account and log in; however, it is not mandatory"><span class="vector-icon mw-ui-icon-userAvatar mw-ui-icon-wikimedia-userAvatar cdx-button__icon"></span>
<span>Create account</span></a>
</li>
<li class="mw-list-item vector-menu-item--collapsible" id="pt-login"><a accesskey="o" class="" data-mw-interface="" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+largest+companies+in+India" title="You're encouraged to log in; however, it's not mandatory. [o]"><span class="vector-icon mw-ui-icon-logIn mw-ui-icon-wikimedia-logIn cdx-button__icon"></span>
<span>Log in</span></a>
</li>
</ul>
</div>
</div>
</div>
</div>
</nav>
</div>
</header>
</div>
<div class="mw-page-container">
<div class="mw-page-container-inner">

In [5]:
soup.find_all('table')[0]

<table class="wikitable sortable" id="mwHw" style="text-align:right;">
<tbody id="mwIA"><tr id="mwIQ"><th align="center" id="mwIg">Rank</th>
<th align="center" id="mwIw">Forbes<br id="mwJA"/> 2000 rank</th>
<th align="center" id="mwJQ">Name</th>
<th align="center" id="mwJg">Headquarters</th>
<th align="center" id="mwJw">Revenue<br id="mwKA"/>(billions US$)</th>
<th align="center" id="mwKQ">Profit<br id="mwKg"/>(billions US$)</th>
<th align="center" id="mwKw">Assets<br id="mwLA"/>(billions US$)</th>
<th align="center" id="mwLQ">Value<br id="mwLg"/>(billions US$)</th>
<th align="center" id="mwLw">Industry</th></tr>
<tr id="mwMA">
<td id="mwMQ">1</td>
<td id="mwMg">49</td>
<td align="left" id="mwMw"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Reliance_Industries_Limited" id="mwNA" rel="mw:WikiLink" title="Reliance Industries Limited">Reliance Industries Limited</a></td>
<td align="left" id="mwNQ">Mumbai</td>
<td id="mwNg">108.8</td>
<td id="mwNw">8.4</td>
<td id="mwOA">210.5</td>
<td id="mwOQ">233.1</td>
<td align="left" id="mwOg"><a href="https://en.wikipedia.org/wiki/Conglomerate_(company)" id="mwOw" rel="mw:WikiLink" title="Conglomerate (company)">Conglomerate</a></td></tr>
<tr id="mwPA">
<td id="mwPQ">2</td>
<td id="mwPg">55</td>
<td align="left" id="mwPw"><a href="https://en.wikipedia.org/wiki/State_Bank_of_India" id="mwQA" rel="mw:WikiLink" title="State Bank of India">State Bank of India</a></td>
<td align="left" id="mwQQ">Mumbai</td>
<td id="mwQg">71.8</td>
<td id="mwQw">8.1</td>
<td id="mwRA">807.4</td>
<td id="mwRQ">87.6</td>
<td align="left" id="mwRg">Banking</td></tr>
<tr id="mwRw">
<td id="mwSA">3</td>
<td id="mwSQ">65</td>
<td align="left" id="mwSg"><a href="https://en.wikipedia.org/wiki/HDFC_Bank" id="mwSw" rel="mw:WikiLink" title="HDFC Bank">HDFC Bank</a></td>
<td align="left" id="mwTA">Mumbai</td>
<td id="mwTQ">49.3</td>
<td id="mwTg">7.7</td>
<td id="mwTw">483.2</td>
<td id="mwUA">133.6</td>
<td align="left" id="mwUQ">Banking</td></tr>
<tr id="mwUg">
<td id="mwUw">4</td>
<td id="mwVA">70</td>
<td align="left" id="mwVQ"><a href="https://en.wikipedia.org/wiki/Life_Insurance_Corporation" id="mwVg" rel="mw:WikiLink" title="Life Insurance Corporation">Life Insurance Corporation</a></td>
<td align="left" id="mwVw">New Delhi</td>
<td id="mwWA">98.0</td>
<td id="mwWQ">4.9</td>
<td id="mwWg">561.4</td>
<td id="mwWw">73.6</td>
<td align="left" id="mwXA">Insurance</td></tr>
<tr id="mwXQ">
<td id="mwXg">5</td>
<td id="mwXw">142</td>
<td align="left" id="mwYA"><a href="https://en.wikipedia.org/wiki/ICICI_Bank" id="mwYQ" rel="mw:WikiLink" title="ICICI Bank">ICICI Bank</a></td>
<td align="left" id="mwYg">Mumbai</td>
<td id="mwYw">28.5</td>
<td id="mwZA">5.3</td>
<td id="mwZQ">283.5</td>
<td id="mwZg">95.3</td>
<td align="left" id="mwZw">Banking</td></tr>
<tr id="mwaA">
<td id="mwaQ">6</td>
<td id="mwag">207</td>
<td align="left" id="mwaw"><a href="https://en.wikipedia.org/wiki/Oil_and_Natural_Gas_Corporation" id="mwbA" rel="mw:WikiLink" title="Oil and Natural Gas Corporation">Oil and Natural Gas Corporation</a></td>
<td align="left" id="mwbQ">New Delhi</td>
<td id="mwbg">77.5</td>
<td id="mwbw">5.1</td>
<td id="mwcA">80.6</td>
<td id="mwcQ">41.9</td>
<td align="left" id="mwcg">Oil and gas</td></tr>
<tr id="mwcw">
<td id="mwdA">7</td>
<td id="mwdQ">259</td>
<td align="left" id="mwdg"><a href="https://en.wikipedia.org/wiki/Indian_Oil_Corporation" id="mwdw" rel="mw:WikiLink" title="Indian Oil Corporation">Indian Oil Corporation</a></td>
<td align="left" id="mweA">New Delhi</td>
<td id="mweQ">93.8</td>
<td id="mweg">5.0</td>
<td id="mwew">57.8</td>
<td id="mwfA">27.8</td>
<td align="left" id="mwfQ"><a href="https://en.wikipedia.org/wiki/Petroleum_industry" id="mwfg" rel="mw:WikiLink" title="Petroleum industry">Oil and gas</a></td></tr>
<tr id="mwfw">
<td id="mwgA">8</td>
<td id="mwgQ">284</td>
<td align="left" id="mwgg"><a href="https://en.wikipedia.org/wiki/Tata_Motors" id="mwgw" rel="mw:WikiLink" title="Tata Motors">Tata Motors</a></td>
<td align="left" id="mwhA">Mumbai</td>
<td id="mwhQ">52.9</td>
<td id="mwhg">3.8</td>
<td id="mwhw">44.4</td>
<td id="mwiA">43.8</td>
<td align="left" id="mwiQ">Automotive</td></tr>
<tr id="mwig">
<td id="mwiw">9</td>
<td id="mwjA">293</td>
<td align="left" id="mwjQ"><a href="https://en.wikipedia.org/wiki/Axis_Bank" id="mwjg" rel="mw:WikiLink" title="Axis Bank">Axis Bank</a></td>
<td align="left" id="mwjw">Mumbai</td>
<td id="mwkA">16.7</td>
<td id="mwkQ">3.2</td>
<td id="mwkg">182.0</td>
<td id="mwkw">42.3</td>
<td align="left" id="mwlA">Banking</td></tr>
<tr id="mwlQ">
<td id="mwlg">10</td>
<td id="mwlw">372</td>
<td align="left" id="mwmA"><a href="https://en.wikipedia.org/wiki/NTPC_Limited" id="mwmQ" rel="mw:WikiLink" title="NTPC Limited">NTPC Limited</a></td>
<td align="left" id="mwmg">New Delhi</td>
<td id="mwmw">21.2</td>
<td id="mwnA">2.4</td>
<td id="mwnQ">54.7</td>
<td id="mwng">42.5</td>
<td align="left" id="mwnw">Utilities</td></tr>
<tr id="mwoA">
<td id="mwoQ">11</td>
<td id="mwog">398</td>
<td align="left" id="mwow"><a href="https://en.wikipedia.org/wiki/Larsen_&amp;_Toubro" id="mwpA" rel="mw:WikiLink" title="Larsen &amp; Toubro">Larsen &amp; Toubro</a></td>
<td align="left" id="mwpQ">Mumbai</td>
<td id="mwpg">26.7</td>
<td id="mwpw">1.6</td>
<td id="mwqA">40.7</td>
<td id="mwqQ">56.9</td>
<td align="left" id="mwqg">Capital goods</td></tr>
<tr id="mwqw">
<td id="mwrA">12</td>
<td id="mwrQ">412</td>
<td align="left" id="mwrg"><a href="https://en.wikipedia.org/wiki/Tata_Consultancy_Services" id="mwrw" rel="mw:WikiLink" title="Tata Consultancy Services">Tata Consultancy Services</a></td>
<td align="left" id="mwsA">Mumbai</td>
<td id="mwsQ">29.1</td>
<td id="mwsg">5.5</td>
<td id="mwsw">17.6</td>
<td id="mwtA">166.5</td>
<td align="left" id="mwtQ">Infotech</td></tr>
<tr id="mwtg">
<td id="mwtw">13</td>
<td id="mwuA">440</td>
<td align="left" id="mwuQ"><a href="https://en.wikipedia.org/wiki/Bank_of_Baroda" id="mwug" rel="mw:WikiLink" title="Bank of Baroda">Bank of Baroda</a></td>
<td align="left" id="mwuw">Vadodara</td>
<td id="mwvA">17.1</td>
<td id="mwvQ">2.3</td>
<td id="mwvg">198.4</td>
<td id="mwvw">16.2</td>
<td align="left" id="mwwA">Banking</td></tr>
<tr id="mwwQ">
<td id="mwwg">14</td>
<td id="mwww">442</td>
<td align="left" id="mwxA"><a href="https://en.wikipedia.org/wiki/Kotak_Mahindra_Bank" id="mwxQ" rel="mw:WikiLink" title="Kotak Mahindra Bank">Kotak Mahindra Bank</a></td>
<td align="left" id="mwxg">Mumbai</td>
<td id="mwxw">11.4</td>
<td id="mwyA">2.2</td>
<td id="mwyQ">92.0</td>
<td id="mwyg">40.5</td>
<td align="left" id="mwyw">Banking</td></tr>
<tr id="mwzA">
<td id="mwzQ">15</td>
<td id="mwzg">472</td>
<td align="left" id="mwzw"><a href="https://en.wikipedia.org/wiki/Bharti_Airtel" id="mw0A" rel="mw:WikiLink" title="Bharti Airtel">Bharti Airtel</a></td>
<td align="left" id="mw0Q">New Delhi</td>
<td id="mw0g">18.1</td>
<td id="mw0w">0.9</td>
<td id="mw1A">53.3</td>
<td id="mw1Q">91.5</td>
<td align="left" id="mw1g">Telecommunication</td></tr>
<tr id="mw1w">
<td id="mw2A">16</td>
<td id="mw2Q">488</td>
<td align="left" id="mw2g"><a href="https://en.wikipedia.org/wiki/Coal_India" id="mw2w" rel="mw:WikiLink" title="Coal India">Coal India</a></td>
<td align="left" id="mw3A">Kolkata</td>
<td id="mw3Q">17.2</td>
<td id="mw3g">3.9</td>
<td id="mw3w">28.5</td>
<td id="mw4A">34.8</td>
<td align="left" id="mw4Q">Metals and mining</td></tr>
<tr id="mw4g">
<td id="mw4w">17</td>
<td id="mw5A">525</td>
<td align="left" id="mw5Q"><a href="https://en.wikipedia.org/wiki/Canara_Bank" id="mw5g" rel="mw:WikiLink" title="Canara Bank">Canara Bank</a></td>
<td align="left" id="mw5w">Bangalore</td>
<td id="mw6A">16.8</td>
<td id="mw6Q">1.8</td>
<td id="mw6g">184.0</td>
<td id="mw6w">12.4</td>
<td align="left" id="mw7A">Banking</td></tr>
<tr id="mw7Q">
<td id="mw7g">18</td>
<td id="mw7w">533</td>
<td align="left" id="mw8A"><a href="https://en.wikipedia.org/wiki/Power_Finance_Corporation" id="mw8Q" rel="mw:WikiLink" title="Power Finance Corporation">Power Finance Corporation</a></td>
<td align="left" id="mw8g">New Delhi</td>
<td id="mw8w">11.1</td>
<td id="mw9A">2.4</td>
<td id="mw9Q">124.6</td>
<td id="mw9g">18.5</td>
<td align="left" id="mw9w">Financials</td></tr>
<tr id="mw-A">
<td id="mw-Q">19</td>
<td id="mw-g">537</td>
<td align="left" id="mw-w"><a href="https://en.wikipedia.org/wiki/Bharat_Petroleum" id="mw_A" rel="mw:WikiLink" title="Bharat Petroleum">Bharat Petroleum</a></td>
<td align="left" id="mw_Q">Mumbai</td>
<td id="mw_g">54.1</td>
<td id="mw_w">3.2</td>
<td id="mwAQA">24.3</td>
<td id="mwAQE">16.4</td>
<td align="left" id="mwAQI">Oil and gas</td></tr>
<tr id="mwAQM">
<td id="mwAQQ">20</td>
<td id="mwAQU">569</td>
<td align="left" id="mwAQY"><a href="https://en.wikipedia.org/wiki/Infosys" id="mwAQc" rel="mw:WikiLink" title="Infosys">Infosys</a></td>
<td align="left" id="mwAQg">Bangalore</td>
<td id="mwAQk">18.6</td>
<td id="mwAQo">3.2</td>
<td id="mwAQs">16.5</td>
<td id="mwAQw">71.9</td>
<td align="left" id="mwAQ0">Infotech</td></tr>
<tr id="mwAQ4">
<td id="mwAQ8">21</td>
<td id="mwARA">571</td>
<td align="left" id="mwARE"><a href="https://en.wikipedia.org/wiki/Punjab_National_Bank" id="mwARI" rel="mw:WikiLink" title="Punjab National Bank">Punjab National Bank</a></td>
<td align="left" id="mwARM">New Delhi</td>
<td id="mwARQ">14.8</td>
<td id="mwARU">1.1</td>
<td id="mwARY">191.7</td>
<td id="mwARc">16.5</td>
<td align="left" id="mwARg">Banking</td></tr>
<tr id="mwARk">
<td id="mwARo">22</td>
<td id="mwARs">575</td>
<td align="left" id="mwARw"><a href="https://en.wikipedia.org/wiki/Union_Bank_of_India" id="mwAR0" rel="mw:WikiLink" title="Union Bank of India">Union Bank of India</a></td>
<td align="left" id="mwAR4">Mumbai</td>
<td id="mwAR8">14.3</td>
<td id="mwASA">1.7</td>
<td id="mwASE">168.1</td>
<td id="mwASI">12.7</td>
<td align="left" id="mwASM">Banking</td></tr>
<tr id="mwASQ">
<td id="mwASU">23</td>
<td id="mwASY">592</td>
<td align="left" id="mwASc"><a href="https://en.wikipedia.org/wiki/Bajaj_Finserv" id="mwASg" rel="mw:WikiLink" title="Bajaj Finserv">Bajaj Finserv</a></td>
<td align="left" id="mwASk">Pune</td>
<td id="mwASo">13.0</td>
<td id="mwASs">1.0</td>
<td id="mwASw">64.5</td>
<td id="mwAS0">30.3</td>
<td align="left" id="mwAS4">Financials</td></tr>
<tr id="mwAS8">
<td id="mwATA">24</td>
<td id="mwATE">593</td>
<td align="left" id="mwATI"><a href="https://en.wikipedia.org/wiki/Mahindra_&amp;_Mahindra" id="mwATM" rel="mw:WikiLink" title="Mahindra &amp; Mahindra">Mahindra &amp; Mahindra</a></td>
<td align="left" id="mwATQ">Mumbai</td>
<td id="mwATU">16.8</td>
<td id="mwATY">1.4</td>
<td id="mwATc">28.3</td>
<td id="mwATg">37.5</td>
<td align="left" id="mwATk">Automotive</td></tr>
<tr id="mwATo">
<td id="mwATs">25</td>
<td id="mwATw">645</td>
<td align="left" id="mwAT0"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/JSW_Steel_Ltd" id="mwAT4" rel="mw:WikiLink" title="JSW Steel Ltd">JSW Steel Ltd</a></td>
<td align="left" id="mwAT8">Mumbai</td>
<td id="mwAUA">21.1</td>
<td id="mwAUE">1.1</td>
<td id="mwAUI">27.4</td>
<td id="mwAUM">26.6</td>
<td align="left" id="mwAUQ">Iron and steel</td></tr>
<tr id="mwAUU">
<td id="mwAUY">26</td>
<td id="mwAUc">684</td>
<td align="left" id="mwAUg"><a href="https://en.wikipedia.org/wiki/Hindalco_Industries" id="mwAUk" rel="mw:WikiLink" title="Hindalco Industries">Hindalco Industries</a></td>
<td align="left" id="mwAUo">Mumbai</td>
<td id="mwAUs">26.1</td>
<td id="mwAUw">1.1</td>
<td id="mwAU0">27.1</td>
<td id="mwAU4">17.7</td>
<td align="left" id="mwAU8">Metals and mining</td></tr>
<tr id="mwAVA">
<td id="mwAVE">27</td>
<td id="mwAVI">746</td>
<td align="left" id="mwAVM"><a href="https://en.wikipedia.org/wiki/Grasim_Industries" id="mwAVQ" rel="mw:WikiLink" title="Grasim Industries">Grasim Industries</a></td>
<td align="left" id="mwAVU">Mumbai</td>
<td id="mwAVY">15.3</td>
<td id="mwAVc">0.7</td>
<td id="mwAVg">47.0</td>
<td id="mwAVk">19.8</td>
<td align="left" id="mwAVo">Diversified</td></tr>
<tr id="mwAVs">
<td id="mwAVw">28</td>
<td id="mwAV0">764</td>
<td align="left" id="mwAV4"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/HCL_Technologies" id="mwAV8" rel="mw:WikiLink" title="HCL Technologies">HCL Technologies</a></td>
<td align="left" id="mwAWA">Noida</td>
<td id="mwAWE">13.3</td>
<td id="mwAWI">1.9</td>
<td id="mwAWM">12.0</td>
<td id="mwAWQ">43.4</td>
<td align="left" id="mwAWU">Infotech</td></tr>
<tr id="mwAWY">
<td id="mwAWc">29</td>
<td id="mwAWg">810</td>
<td align="left" id="mwAWk"><a href="https://en.wikipedia.org/wiki/ITC_Limited" id="mwAWo" rel="mw:WikiLink" title="ITC Limited">ITC Limited</a></td>
<td align="left" id="mwAWs">Kolkata</td>
<td id="mwAWw">8.5</td>
<td id="mwAW0">2.5</td>
<td id="mwAW4">10.5</td>
<td id="mwAW8">65.4</td>
<td align="left" id="mwAXA">Consumer goods</td></tr>
<tr id="mwAXE">
<td id="mwAXI">30</td>
<td id="mwAXM">827</td>
<td align="left" id="mwAXQ"><a href="https://en.wikipedia.org/wiki/Power_Grid_Corporation_of_India" id="mwAXU" rel="mw:WikiLink" title="Power Grid Corporation of India">Power Grid Corporation of India</a></td>
<td align="left" id="mwAXY">Gurgaon</td>
<td id="mwAXc">5.6</td>
<td id="mwAXg">1.9</td>
<td id="mwAXk">29.6</td>
<td id="mwAXo">35.0</td>
<td align="left" id="mwAXs">Utilities</td></tr>
<tr id="mwAXw">
<td id="mwAX0">31</td>
<td id="mwAX4">834</td>
<td align="left" id="mwAX8"><a href="https://en.wikipedia.org/wiki/Tata_Steel" id="mwAYA" rel="mw:WikiLink" title="Tata Steel">Tata Steel</a></td>
<td align="left" id="mwAYE">Kolkata</td>
<td id="mwAYI">28.3</td>
<td id="mwAYM">−0.4</td>
<td id="mwAYQ">32.7</td>
<td id="mwAYU">25.1</td>
<td align="left" id="mwAYY">Iron and steel</td></tr>
<tr id="mwAYc">
<td id="mwAYg">32</td>
<td id="mwAYk">901</td>
<td align="left" id="mwAYo"><a href="https://en.wikipedia.org/wiki/IndusInd_Bank" id="mwAYs" rel="mw:WikiLink" title="IndusInd Bank">IndusInd Bank</a></td>
<td align="left" id="mwAYw">Mumbai</td>
<td id="mwAY0">6.7</td>
<td id="mwAY4">1.1</td>
<td id="mwAY8">61.8</td>
<td id="mwAZA">13.2</td>
<td align="left" id="mwAZE">Banking</td></tr>
<tr id="mwAZI">
<td id="mwAZM">33</td>
<td id="mwAZQ">922</td>
<td align="left" id="mwAZU"><a href="https://en.wikipedia.org/wiki/Indian_Railway_Finance_Corporation" id="mwAZY" rel="mw:WikiLink" title="Indian Railway Finance Corporation">Indian Railway Finance Corporation</a></td>
<td align="left" id="mwAZc">New Delhi</td>
<td id="mwAZg">3.2</td>
<td id="mwAZk">0.7</td>
<td id="mwAZo">58.6</td>
<td id="mwAZs">26.5</td>
<td align="left" id="mwAZw">Financials</td></tr>
<tr id="mwAZ0">
<td id="mwAZ4">34</td>
<td id="mwAZ8">926</td>
<td align="left" id="mwAaA"><a href="https://en.wikipedia.org/wiki/Wipro" id="mwAaE" rel="mw:WikiLink" title="Wipro">Wipro</a></td>
<td align="left" id="mwAaI">Bangalore</td>
<td id="mwAaM">10.8</td>
<td id="mwAaQ">1.3</td>
<td id="mwAaU">13.8</td>
<td id="mwAaY">28.9</td>
<td align="left" id="mwAac">Infotech</td></tr>
<tr id="mwAag">
<td id="mwAak">35</td>
<td id="mwAao">930</td>
<td align="left" id="mwAas"><a href="https://en.wikipedia.org/wiki/GAIL" id="mwAaw" rel="mw:WikiLink" title="GAIL">GAIL</a></td>
<td align="left" id="mwAa0">New Delhi</td>
<td id="mwAa4">16.1</td>
<td id="mwAa8">1.2</td>
<td id="mwAbA">15.0</td>
<td id="mwAbE">16.1</td>
<td align="left" id="mwAbI">Oil and gas</td></tr>
<tr id="mwAbM">
<td id="mwAbQ">36</td>
<td id="mwAbU">947</td>
<td align="left" id="mwAbY"><a href="https://en.wikipedia.org/wiki/Indian_Bank" id="mwAbc" rel="mw:WikiLink" title="Indian Bank">Indian Bank</a></td>
<td align="left" id="mwAbg">Chennai</td>
<td id="mwAbk">7.8</td>
<td id="mwAbo">1.0</td>
<td id="mwAbs">95.4</td>
<td id="mwAbw">8.7</td>
<td align="left" id="mwAb0">Banking</td></tr>
<tr id="mwAb4">
<td id="mwAb8">37</td>
<td id="mwAcA">961</td>
<td align="left" id="mwAcE"><a href="https://en.wikipedia.org/wiki/Vedanta_Limited" id="mwAcI" rel="mw:WikiLink" title="Vedanta Limited">Vedanta Limited</a></td>
<td align="left" id="mwAcM">Mumbai</td>
<td id="mwAcQ">17.4</td>
<td id="mwAcU">0.5</td>
<td id="mwAcY">22.9</td>
<td id="mwAcc">19.7</td>
<td align="left" id="mwAcg">Metals and mining</td></tr>
<tr id="mwAck">
<td id="mwAco">38</td>
<td id="mwAcs">1048</td>
<td align="left" id="mwAcw"><a href="https://en.wikipedia.org/wiki/Adani_Power" id="mwAc0" rel="mw:WikiLink" title="Adani Power">Adani Power</a></td>
<td align="left" id="mwAc4"><a href="https://en.wikipedia.org/wiki/Ahmedabad" id="mwAc8" rel="mw:WikiLink" title="Ahmedabad">Ahmedabad</a></td>
<td id="mwAdA">6.1</td>
<td id="mwAdE">2.5</td>
<td id="mwAdI">11.1</td>
<td id="mwAdM">29.4</td>
<td align="left" id="mwAdQ"><a href="https://en.wikipedia.org/wiki/Energy" id="mwAdU" rel="mw:WikiLink" title="Energy">Energy</a></td></tr>
<tr id="mwAdY">
<td id="mwAdc">39</td>
<td id="mwAdg">1053</td>
<td align="left" id="mwAdk"><a href="https://en.wikipedia.org/wiki/Bank_of_India" id="mwAdo" rel="mw:WikiLink" title="Bank of India">Bank of India</a></td>
<td align="left" id="mwAds">Mumbai</td>
<td id="mwAdw">8.1</td>
<td id="mwAd0">0.8</td>
<td id="mwAd4">110.8</td>
<td id="mwAd8">6.7</td>
<td align="left" id="mwAeA">Banking</td></tr>
<tr id="mwAeE">
<td id="mwAeI">40</td>
<td id="mwAeM">1059</td>
<td align="left" id="mwAeQ"><a href="https://en.wikipedia.org/wiki/Adani_Enterprises" id="mwAeU" rel="mw:WikiLink" title="Adani Enterprises">Adani Enterprises</a></td>
<td align="left" id="mwAeY">Ahmedabad</td>
<td id="mwAec">12.7</td>
<td id="mwAeg">0.4</td>
<td id="mwAek">19.3</td>
<td id="mwAeo">41.9</td>
<td align="left" id="mwAes">Holding</td></tr>
<tr id="mwAew">
<td id="mwAe0">41</td>
<td id="mwAe4">1161</td>
<td align="left" id="mwAe8"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Sun_Pharmaceutical" id="mwAfA" rel="mw:WikiLink" title="Sun Pharmaceutical">Sun Pharmaceutical</a></td>
<td align="left" id="mwAfE">Mumbai</td>
<td id="mwAfI">5.7</td>
<td id="mwAfM">1.1</td>
<td id="mwAfQ">9.6</td>
<td id="mwAfU">44.1</td>
<td align="left" id="mwAfY"><a href="https://en.wikipedia.org/wiki/Pharmaceutical_industry" id="mwAfc" rel="mw:WikiLink" title="Pharmaceutical industry">Pharmaceuticals</a></td></tr>
<tr id="mwAfg">
<td id="mwAfk">42</td>
<td id="mwAfo">1212</td>
<td align="left" id="mwAfs"><a href="https://en.wikipedia.org/wiki/IndiGo" id="mwAfw" rel="mw:WikiLink" title="IndiGo">IndiGo</a></td>
<td align="left" id="mwAf0">Gurgaon</td>
<td id="mwAf4">7.9</td>
<td id="mwAf8">0.9</td>
<td id="mwAgA">8.8</td>
<td id="mwAgE">20.2</td>
<td align="left" id="mwAgI"><a href="https://en.wikipedia.org/wiki/Airline" id="mwAgM" rel="mw:WikiLink" title="Airline">Airline</a></td></tr>
<tr id="mwAgQ">
<td id="mwAgU">43</td>
<td id="mwAgY">1219</td>
<td align="left" id="mwAgc"><a href="https://en.wikipedia.org/wiki/Adani_Ports_&amp;_SEZ" id="mwAgg" rel="mw:WikiLink" title="Adani Ports &amp; SEZ">Adani Ports &amp; SEZ</a></td>
<td align="left" id="mwAgk">Ahmedabad</td>
<td id="mwAgo">3.2</td>
<td id="mwAgs">1.0</td>
<td id="mwAgw">14.3</td>
<td id="mwAg0">34.6</td>
<td align="left" id="mwAg4"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Shipping" id="mwAg8" rel="mw:WikiLink" title="Shipping">Shipping</a></td></tr>
<tr id="mwAhA">
<td id="mwAhE">44</td>
<td id="mwAhI">1259</td>
<td align="left" id="mwAhM"><a href="https://en.wikipedia.org/wiki/IDBI_Bank" id="mwAhQ" rel="mw:WikiLink" title="IDBI Bank">IDBI Bank</a></td>
<td align="left" id="mwAhU">Mumbai</td>
<td id="mwAhY">3.7</td>
<td id="mwAhc">0.7</td>
<td id="mwAhg">43.7</td>
<td id="mwAhk">10.9</td>
<td align="left" id="mwAho">Banking</td></tr>
<tr id="mwAhs">
<td id="mwAhw">45</td>
<td id="mwAh0">1264</td>
<td align="left" id="mwAh4"><a href="https://en.wikipedia.org/wiki/Bajaj_Auto" id="mwAh8" rel="mw:WikiLink" title="Bajaj Auto">Bajaj Auto</a></td>
<td align="left" id="mwAiA">Pune</td>
<td id="mwAiE">5.4</td>
<td id="mwAiI">0.9</td>
<td id="mwAiM">4.7</td>
<td id="mwAiQ">29.4</td>

In [6]:
soup.find('table', class_ = 'wikitable sortable')

<table class="wikitable sortable" id="mwHw" style="text-align:right;">
<tbody id="mwIA"><tr id="mwIQ"><th align="center" id="mwIg">Rank</th>
<th align="center" id="mwIw">Forbes<br id="mwJA"/> 2000 rank</th>
<th align="center" id="mwJQ">Name</th>
<th align="center" id="mwJg">Headquarters</th>
<th align="center" id="mwJw">Revenue<br id="mwKA"/>(billions US$)</th>
<th align="center" id="mwKQ">Profit<br id="mwKg"/>(billions US$)</th>
<th align="center" id="mwKw">Assets<br id="mwLA"/>(billions US$)</th>
<th align="center" id="mwLQ">Value<br id="mwLg"/>(billions US$)</th>
<th align="center" id="mwLw">Industry</th></tr>
<tr id="mwMA">
<td id="mwMQ">1</td>
<td id="mwMg">49</td>
<td align="left" id="mwMw"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Reliance_Industries_Limited" id="mwNA" rel="mw:WikiLink" title="Reliance Industries Limited">Reliance Industries Limited</a></td>
<td align="left" id="mwNQ">Mumbai</td>
<td id="mwNg">108.8</td>
<td id="mwNw">8.4</td>
<td id="mwOA">210.5</td>
<td id="mwOQ">233.1</td>
<td align="left" id="mwOg"><a href="https://en.wikipedia.org/wiki/Conglomerate_(company)" id="mwOw" rel="mw:WikiLink" title="Conglomerate (company)">Conglomerate</a></td></tr>
<tr id="mwPA">
<td id="mwPQ">2</td>
<td id="mwPg">55</td>
<td align="left" id="mwPw"><a href="https://en.wikipedia.org/wiki/State_Bank_of_India" id="mwQA" rel="mw:WikiLink" title="State Bank of India">State Bank of India</a></td>
<td align="left" id="mwQQ">Mumbai</td>
<td id="mwQg">71.8</td>
<td id="mwQw">8.1</td>
<td id="mwRA">807.4</td>
<td id="mwRQ">87.6</td>
<td align="left" id="mwRg">Banking</td></tr>
<tr id="mwRw">
<td id="mwSA">3</td>
<td id="mwSQ">65</td>
<td align="left" id="mwSg"><a href="https://en.wikipedia.org/wiki/HDFC_Bank" id="mwSw" rel="mw:WikiLink" title="HDFC Bank">HDFC Bank</a></td>
<td align="left" id="mwTA">Mumbai</td>
<td id="mwTQ">49.3</td>
<td id="mwTg">7.7</td>
<td id="mwTw">483.2</td>
<td id="mwUA">133.6</td>
<td align="left" id="mwUQ">Banking</td></tr>
<tr id="mwUg">
<td id="mwUw">4</td>
<td id="mwVA">70</td>
<td align="left" id="mwVQ"><a href="https://en.wikipedia.org/wiki/Life_Insurance_Corporation" id="mwVg" rel="mw:WikiLink" title="Life Insurance Corporation">Life Insurance Corporation</a></td>
<td align="left" id="mwVw">New Delhi</td>
<td id="mwWA">98.0</td>
<td id="mwWQ">4.9</td>
<td id="mwWg">561.4</td>
<td id="mwWw">73.6</td>
<td align="left" id="mwXA">Insurance</td></tr>
<tr id="mwXQ">
<td id="mwXg">5</td>
<td id="mwXw">142</td>
<td align="left" id="mwYA"><a href="https://en.wikipedia.org/wiki/ICICI_Bank" id="mwYQ" rel="mw:WikiLink" title="ICICI Bank">ICICI Bank</a></td>
<td align="left" id="mwYg">Mumbai</td>
<td id="mwYw">28.5</td>
<td id="mwZA">5.3</td>
<td id="mwZQ">283.5</td>
<td id="mwZg">95.3</td>
<td align="left" id="mwZw">Banking</td></tr>
<tr id="mwaA">
<td id="mwaQ">6</td>
<td id="mwag">207</td>
<td align="left" id="mwaw"><a href="https://en.wikipedia.org/wiki/Oil_and_Natural_Gas_Corporation" id="mwbA" rel="mw:WikiLink" title="Oil and Natural Gas Corporation">Oil and Natural Gas Corporation</a></td>
<td align="left" id="mwbQ">New Delhi</td>
<td id="mwbg">77.5</td>
<td id="mwbw">5.1</td>
<td id="mwcA">80.6</td>
<td id="mwcQ">41.9</td>
<td align="left" id="mwcg">Oil and gas</td></tr>
<tr id="mwcw">
<td id="mwdA">7</td>
<td id="mwdQ">259</td>
<td align="left" id="mwdg"><a href="https://en.wikipedia.org/wiki/Indian_Oil_Corporation" id="mwdw" rel="mw:WikiLink" title="Indian Oil Corporation">Indian Oil Corporation</a></td>
<td align="left" id="mweA">New Delhi</td>
<td id="mweQ">93.8</td>
<td id="mweg">5.0</td>
<td id="mwew">57.8</td>
<td id="mwfA">27.8</td>
<td align="left" id="mwfQ"><a href="https://en.wikipedia.org/wiki/Petroleum_industry" id="mwfg" rel="mw:WikiLink" title="Petroleum industry">Oil and gas</a></td></tr>
<tr id="mwfw">
<td id="mwgA">8</td>
<td id="mwgQ">284</td>
<td align="left" id="mwgg"><a href="https://en.wikipedia.org/wiki/Tata_Motors" id="mwgw" rel="mw:WikiLink" title="Tata Motors">Tata Motors</a></td>
<td align="left" id="mwhA">Mumbai</td>
<td id="mwhQ">52.9</td>
<td id="mwhg">3.8</td>
<td id="mwhw">44.4</td>
<td id="mwiA">43.8</td>
<td align="left" id="mwiQ">Automotive</td></tr>
<tr id="mwig">
<td id="mwiw">9</td>
<td id="mwjA">293</td>
<td align="left" id="mwjQ"><a href="https://en.wikipedia.org/wiki/Axis_Bank" id="mwjg" rel="mw:WikiLink" title="Axis Bank">Axis Bank</a></td>
<td align="left" id="mwjw">Mumbai</td>
<td id="mwkA">16.7</td>
<td id="mwkQ">3.2</td>
<td id="mwkg">182.0</td>
<td id="mwkw">42.3</td>
<td align="left" id="mwlA">Banking</td></tr>
<tr id="mwlQ">
<td id="mwlg">10</td>
<td id="mwlw">372</td>
<td align="left" id="mwmA"><a href="https://en.wikipedia.org/wiki/NTPC_Limited" id="mwmQ" rel="mw:WikiLink" title="NTPC Limited">NTPC Limited</a></td>
<td align="left" id="mwmg">New Delhi</td>
<td id="mwmw">21.2</td>
<td id="mwnA">2.4</td>
<td id="mwnQ">54.7</td>
<td id="mwng">42.5</td>
<td align="left" id="mwnw">Utilities</td></tr>
<tr id="mwoA">
<td id="mwoQ">11</td>
<td id="mwog">398</td>
<td align="left" id="mwow"><a href="https://en.wikipedia.org/wiki/Larsen_&amp;_Toubro" id="mwpA" rel="mw:WikiLink" title="Larsen &amp; Toubro">Larsen &amp; Toubro</a></td>
<td align="left" id="mwpQ">Mumbai</td>
<td id="mwpg">26.7</td>
<td id="mwpw">1.6</td>
<td id="mwqA">40.7</td>
<td id="mwqQ">56.9</td>
<td align="left" id="mwqg">Capital goods</td></tr>
<tr id="mwqw">
<td id="mwrA">12</td>
<td id="mwrQ">412</td>
<td align="left" id="mwrg"><a href="https://en.wikipedia.org/wiki/Tata_Consultancy_Services" id="mwrw" rel="mw:WikiLink" title="Tata Consultancy Services">Tata Consultancy Services</a></td>
<td align="left" id="mwsA">Mumbai</td>
<td id="mwsQ">29.1</td>
<td id="mwsg">5.5</td>
<td id="mwsw">17.6</td>
<td id="mwtA">166.5</td>
<td align="left" id="mwtQ">Infotech</td></tr>
<tr id="mwtg">
<td id="mwtw">13</td>
<td id="mwuA">440</td>
<td align="left" id="mwuQ"><a href="https://en.wikipedia.org/wiki/Bank_of_Baroda" id="mwug" rel="mw:WikiLink" title="Bank of Baroda">Bank of Baroda</a></td>
<td align="left" id="mwuw">Vadodara</td>
<td id="mwvA">17.1</td>
<td id="mwvQ">2.3</td>
<td id="mwvg">198.4</td>
<td id="mwvw">16.2</td>
<td align="left" id="mwwA">Banking</td></tr>
<tr id="mwwQ">
<td id="mwwg">14</td>
<td id="mwww">442</td>
<td align="left" id="mwxA"><a href="https://en.wikipedia.org/wiki/Kotak_Mahindra_Bank" id="mwxQ" rel="mw:WikiLink" title="Kotak Mahindra Bank">Kotak Mahindra Bank</a></td>
<td align="left" id="mwxg">Mumbai</td>
<td id="mwxw">11.4</td>
<td id="mwyA">2.2</td>
<td id="mwyQ">92.0</td>
<td id="mwyg">40.5</td>
<td align="left" id="mwyw">Banking</td></tr>
<tr id="mwzA">
<td id="mwzQ">15</td>
<td id="mwzg">472</td>
<td align="left" id="mwzw"><a href="https://en.wikipedia.org/wiki/Bharti_Airtel" id="mw0A" rel="mw:WikiLink" title="Bharti Airtel">Bharti Airtel</a></td>
<td align="left" id="mw0Q">New Delhi</td>
<td id="mw0g">18.1</td>
<td id="mw0w">0.9</td>
<td id="mw1A">53.3</td>
<td id="mw1Q">91.5</td>
<td align="left" id="mw1g">Telecommunication</td></tr>
<tr id="mw1w">
<td id="mw2A">16</td>
<td id="mw2Q">488</td>
<td align="left" id="mw2g"><a href="https://en.wikipedia.org/wiki/Coal_India" id="mw2w" rel="mw:WikiLink" title="Coal India">Coal India</a></td>
<td align="left" id="mw3A">Kolkata</td>
<td id="mw3Q">17.2</td>
<td id="mw3g">3.9</td>
<td id="mw3w">28.5</td>
<td id="mw4A">34.8</td>
<td align="left" id="mw4Q">Metals and mining</td></tr>
<tr id="mw4g">
<td id="mw4w">17</td>
<td id="mw5A">525</td>
<td align="left" id="mw5Q"><a href="https://en.wikipedia.org/wiki/Canara_Bank" id="mw5g" rel="mw:WikiLink" title="Canara Bank">Canara Bank</a></td>
<td align="left" id="mw5w">Bangalore</td>
<td id="mw6A">16.8</td>
<td id="mw6Q">1.8</td>
<td id="mw6g">184.0</td>
<td id="mw6w">12.4</td>
<td align="left" id="mw7A">Banking</td></tr>
<tr id="mw7Q">
<td id="mw7g">18</td>
<td id="mw7w">533</td>
<td align="left" id="mw8A"><a href="https://en.wikipedia.org/wiki/Power_Finance_Corporation" id="mw8Q" rel="mw:WikiLink" title="Power Finance Corporation">Power Finance Corporation</a></td>
<td align="left" id="mw8g">New Delhi</td>
<td id="mw8w">11.1</td>
<td id="mw9A">2.4</td>
<td id="mw9Q">124.6</td>
<td id="mw9g">18.5</td>
<td align="left" id="mw9w">Financials</td></tr>
<tr id="mw-A">
<td id="mw-Q">19</td>
<td id="mw-g">537</td>
<td align="left" id="mw-w"><a href="https://en.wikipedia.org/wiki/Bharat_Petroleum" id="mw_A" rel="mw:WikiLink" title="Bharat Petroleum">Bharat Petroleum</a></td>
<td align="left" id="mw_Q">Mumbai</td>
<td id="mw_g">54.1</td>
<td id="mw_w">3.2</td>
<td id="mwAQA">24.3</td>
<td id="mwAQE">16.4</td>
<td align="left" id="mwAQI">Oil and gas</td></tr>
<tr id="mwAQM">
<td id="mwAQQ">20</td>
<td id="mwAQU">569</td>
<td align="left" id="mwAQY"><a href="https://en.wikipedia.org/wiki/Infosys" id="mwAQc" rel="mw:WikiLink" title="Infosys">Infosys</a></td>
<td align="left" id="mwAQg">Bangalore</td>
<td id="mwAQk">18.6</td>
<td id="mwAQo">3.2</td>
<td id="mwAQs">16.5</td>
<td id="mwAQw">71.9</td>
<td align="left" id="mwAQ0">Infotech</td></tr>
<tr id="mwAQ4">
<td id="mwAQ8">21</td>
<td id="mwARA">571</td>
<td align="left" id="mwARE"><a href="https://en.wikipedia.org/wiki/Punjab_National_Bank" id="mwARI" rel="mw:WikiLink" title="Punjab National Bank">Punjab National Bank</a></td>
<td align="left" id="mwARM">New Delhi</td>
<td id="mwARQ">14.8</td>
<td id="mwARU">1.1</td>
<td id="mwARY">191.7</td>
<td id="mwARc">16.5</td>
<td align="left" id="mwARg">Banking</td></tr>
<tr id="mwARk">
<td id="mwARo">22</td>
<td id="mwARs">575</td>
<td align="left" id="mwARw"><a href="https://en.wikipedia.org/wiki/Union_Bank_of_India" id="mwAR0" rel="mw:WikiLink" title="Union Bank of India">Union Bank of India</a></td>
<td align="left" id="mwAR4">Mumbai</td>
<td id="mwAR8">14.3</td>
<td id="mwASA">1.7</td>
<td id="mwASE">168.1</td>
<td id="mwASI">12.7</td>
<td align="left" id="mwASM">Banking</td></tr>
<tr id="mwASQ">
<td id="mwASU">23</td>
<td id="mwASY">592</td>
<td align="left" id="mwASc"><a href="https://en.wikipedia.org/wiki/Bajaj_Finserv" id="mwASg" rel="mw:WikiLink" title="Bajaj Finserv">Bajaj Finserv</a></td>
<td align="left" id="mwASk">Pune</td>
<td id="mwASo">13.0</td>
<td id="mwASs">1.0</td>
<td id="mwASw">64.5</td>
<td id="mwAS0">30.3</td>
<td align="left" id="mwAS4">Financials</td></tr>
<tr id="mwAS8">
<td id="mwATA">24</td>
<td id="mwATE">593</td>
<td align="left" id="mwATI"><a href="https://en.wikipedia.org/wiki/Mahindra_&amp;_Mahindra" id="mwATM" rel="mw:WikiLink" title="Mahindra &amp; Mahindra">Mahindra &amp; Mahindra</a></td>
<td align="left" id="mwATQ">Mumbai</td>
<td id="mwATU">16.8</td>
<td id="mwATY">1.4</td>
<td id="mwATc">28.3</td>
<td id="mwATg">37.5</td>
<td align="left" id="mwATk">Automotive</td></tr>
<tr id="mwATo">
<td id="mwATs">25</td>
<td id="mwATw">645</td>
<td align="left" id="mwAT0"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/JSW_Steel_Ltd" id="mwAT4" rel="mw:WikiLink" title="JSW Steel Ltd">JSW Steel Ltd</a></td>
<td align="left" id="mwAT8">Mumbai</td>
<td id="mwAUA">21.1</td>
<td id="mwAUE">1.1</td>
<td id="mwAUI">27.4</td>
<td id="mwAUM">26.6</td>
<td align="left" id="mwAUQ">Iron and steel</td></tr>
<tr id="mwAUU">
<td id="mwAUY">26</td>
<td id="mwAUc">684</td>
<td align="left" id="mwAUg"><a href="https://en.wikipedia.org/wiki/Hindalco_Industries" id="mwAUk" rel="mw:WikiLink" title="Hindalco Industries">Hindalco Industries</a></td>
<td align="left" id="mwAUo">Mumbai</td>
<td id="mwAUs">26.1</td>
<td id="mwAUw">1.1</td>
<td id="mwAU0">27.1</td>
<td id="mwAU4">17.7</td>
<td align="left" id="mwAU8">Metals and mining</td></tr>
<tr id="mwAVA">
<td id="mwAVE">27</td>
<td id="mwAVI">746</td>
<td align="left" id="mwAVM"><a href="https://en.wikipedia.org/wiki/Grasim_Industries" id="mwAVQ" rel="mw:WikiLink" title="Grasim Industries">Grasim Industries</a></td>
<td align="left" id="mwAVU">Mumbai</td>
<td id="mwAVY">15.3</td>
<td id="mwAVc">0.7</td>
<td id="mwAVg">47.0</td>
<td id="mwAVk">19.8</td>
<td align="left" id="mwAVo">Diversified</td></tr>
<tr id="mwAVs">
<td id="mwAVw">28</td>
<td id="mwAV0">764</td>
<td align="left" id="mwAV4"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/HCL_Technologies" id="mwAV8" rel="mw:WikiLink" title="HCL Technologies">HCL Technologies</a></td>
<td align="left" id="mwAWA">Noida</td>
<td id="mwAWE">13.3</td>
<td id="mwAWI">1.9</td>
<td id="mwAWM">12.0</td>
<td id="mwAWQ">43.4</td>
<td align="left" id="mwAWU">Infotech</td></tr>
<tr id="mwAWY">
<td id="mwAWc">29</td>
<td id="mwAWg">810</td>
<td align="left" id="mwAWk"><a href="https://en.wikipedia.org/wiki/ITC_Limited" id="mwAWo" rel="mw:WikiLink" title="ITC Limited">ITC Limited</a></td>
<td align="left" id="mwAWs">Kolkata</td>
<td id="mwAWw">8.5</td>
<td id="mwAW0">2.5</td>
<td id="mwAW4">10.5</td>
<td id="mwAW8">65.4</td>
<td align="left" id="mwAXA">Consumer goods</td></tr>
<tr id="mwAXE">
<td id="mwAXI">30</td>
<td id="mwAXM">827</td>
<td align="left" id="mwAXQ"><a href="https://en.wikipedia.org/wiki/Power_Grid_Corporation_of_India" id="mwAXU" rel="mw:WikiLink" title="Power Grid Corporation of India">Power Grid Corporation of India</a></td>
<td align="left" id="mwAXY">Gurgaon</td>
<td id="mwAXc">5.6</td>
<td id="mwAXg">1.9</td>
<td id="mwAXk">29.6</td>
<td id="mwAXo">35.0</td>
<td align="left" id="mwAXs">Utilities</td></tr>
<tr id="mwAXw">
<td id="mwAX0">31</td>
<td id="mwAX4">834</td>
<td align="left" id="mwAX8"><a href="https://en.wikipedia.org/wiki/Tata_Steel" id="mwAYA" rel="mw:WikiLink" title="Tata Steel">Tata Steel</a></td>
<td align="left" id="mwAYE">Kolkata</td>
<td id="mwAYI">28.3</td>
<td id="mwAYM">−0.4</td>
<td id="mwAYQ">32.7</td>
<td id="mwAYU">25.1</td>
<td align="left" id="mwAYY">Iron and steel</td></tr>
<tr id="mwAYc">
<td id="mwAYg">32</td>
<td id="mwAYk">901</td>
<td align="left" id="mwAYo"><a href="https://en.wikipedia.org/wiki/IndusInd_Bank" id="mwAYs" rel="mw:WikiLink" title="IndusInd Bank">IndusInd Bank</a></td>
<td align="left" id="mwAYw">Mumbai</td>
<td id="mwAY0">6.7</td>
<td id="mwAY4">1.1</td>
<td id="mwAY8">61.8</td>
<td id="mwAZA">13.2</td>
<td align="left" id="mwAZE">Banking</td></tr>
<tr id="mwAZI">
<td id="mwAZM">33</td>
<td id="mwAZQ">922</td>
<td align="left" id="mwAZU"><a href="https://en.wikipedia.org/wiki/Indian_Railway_Finance_Corporation" id="mwAZY" rel="mw:WikiLink" title="Indian Railway Finance Corporation">Indian Railway Finance Corporation</a></td>
<td align="left" id="mwAZc">New Delhi</td>
<td id="mwAZg">3.2</td>
<td id="mwAZk">0.7</td>
<td id="mwAZo">58.6</td>
<td id="mwAZs">26.5</td>
<td align="left" id="mwAZw">Financials</td></tr>
<tr id="mwAZ0">
<td id="mwAZ4">34</td>
<td id="mwAZ8">926</td>
<td align="left" id="mwAaA"><a href="https://en.wikipedia.org/wiki/Wipro" id="mwAaE" rel="mw:WikiLink" title="Wipro">Wipro</a></td>
<td align="left" id="mwAaI">Bangalore</td>
<td id="mwAaM">10.8</td>
<td id="mwAaQ">1.3</td>
<td id="mwAaU">13.8</td>
<td id="mwAaY">28.9</td>
<td align="left" id="mwAac">Infotech</td></tr>
<tr id="mwAag">
<td id="mwAak">35</td>
<td id="mwAao">930</td>
<td align="left" id="mwAas"><a href="https://en.wikipedia.org/wiki/GAIL" id="mwAaw" rel="mw:WikiLink" title="GAIL">GAIL</a></td>
<td align="left" id="mwAa0">New Delhi</td>
<td id="mwAa4">16.1</td>
<td id="mwAa8">1.2</td>
<td id="mwAbA">15.0</td>
<td id="mwAbE">16.1</td>
<td align="left" id="mwAbI">Oil and gas</td></tr>
<tr id="mwAbM">
<td id="mwAbQ">36</td>
<td id="mwAbU">947</td>
<td align="left" id="mwAbY"><a href="https://en.wikipedia.org/wiki/Indian_Bank" id="mwAbc" rel="mw:WikiLink" title="Indian Bank">Indian Bank</a></td>
<td align="left" id="mwAbg">Chennai</td>
<td id="mwAbk">7.8</td>
<td id="mwAbo">1.0</td>
<td id="mwAbs">95.4</td>
<td id="mwAbw">8.7</td>
<td align="left" id="mwAb0">Banking</td></tr>
<tr id="mwAb4">
<td id="mwAb8">37</td>
<td id="mwAcA">961</td>
<td align="left" id="mwAcE"><a href="https://en.wikipedia.org/wiki/Vedanta_Limited" id="mwAcI" rel="mw:WikiLink" title="Vedanta Limited">Vedanta Limited</a></td>
<td align="left" id="mwAcM">Mumbai</td>
<td id="mwAcQ">17.4</td>
<td id="mwAcU">0.5</td>
<td id="mwAcY">22.9</td>
<td id="mwAcc">19.7</td>
<td align="left" id="mwAcg">Metals and mining</td></tr>
<tr id="mwAck">
<td id="mwAco">38</td>
<td id="mwAcs">1048</td>
<td align="left" id="mwAcw"><a href="https://en.wikipedia.org/wiki/Adani_Power" id="mwAc0" rel="mw:WikiLink" title="Adani Power">Adani Power</a></td>
<td align="left" id="mwAc4"><a href="https://en.wikipedia.org/wiki/Ahmedabad" id="mwAc8" rel="mw:WikiLink" title="Ahmedabad">Ahmedabad</a></td>
<td id="mwAdA">6.1</td>
<td id="mwAdE">2.5</td>
<td id="mwAdI">11.1</td>
<td id="mwAdM">29.4</td>
<td align="left" id="mwAdQ"><a href="https://en.wikipedia.org/wiki/Energy" id="mwAdU" rel="mw:WikiLink" title="Energy">Energy</a></td></tr>
<tr id="mwAdY">
<td id="mwAdc">39</td>
<td id="mwAdg">1053</td>
<td align="left" id="mwAdk"><a href="https://en.wikipedia.org/wiki/Bank_of_India" id="mwAdo" rel="mw:WikiLink" title="Bank of India">Bank of India</a></td>
<td align="left" id="mwAds">Mumbai</td>
<td id="mwAdw">8.1</td>
<td id="mwAd0">0.8</td>
<td id="mwAd4">110.8</td>
<td id="mwAd8">6.7</td>
<td align="left" id="mwAeA">Banking</td></tr>
<tr id="mwAeE">
<td id="mwAeI">40</td>
<td id="mwAeM">1059</td>
<td align="left" id="mwAeQ"><a href="https://en.wikipedia.org/wiki/Adani_Enterprises" id="mwAeU" rel="mw:WikiLink" title="Adani Enterprises">Adani Enterprises</a></td>
<td align="left" id="mwAeY">Ahmedabad</td>
<td id="mwAec">12.7</td>
<td id="mwAeg">0.4</td>
<td id="mwAek">19.3</td>
<td id="mwAeo">41.9</td>
<td align="left" id="mwAes">Holding</td></tr>
<tr id="mwAew">
<td id="mwAe0">41</td>
<td id="mwAe4">1161</td>
<td align="left" id="mwAe8"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Sun_Pharmaceutical" id="mwAfA" rel="mw:WikiLink" title="Sun Pharmaceutical">Sun Pharmaceutical</a></td>
<td align="left" id="mwAfE">Mumbai</td>
<td id="mwAfI">5.7</td>
<td id="mwAfM">1.1</td>
<td id="mwAfQ">9.6</td>
<td id="mwAfU">44.1</td>
<td align="left" id="mwAfY"><a href="https://en.wikipedia.org/wiki/Pharmaceutical_industry" id="mwAfc" rel="mw:WikiLink" title="Pharmaceutical industry">Pharmaceuticals</a></td></tr>
<tr id="mwAfg">
<td id="mwAfk">42</td>
<td id="mwAfo">1212</td>
<td align="left" id="mwAfs"><a href="https://en.wikipedia.org/wiki/IndiGo" id="mwAfw" rel="mw:WikiLink" title="IndiGo">IndiGo</a></td>
<td align="left" id="mwAf0">Gurgaon</td>
<td id="mwAf4">7.9</td>
<td id="mwAf8">0.9</td>
<td id="mwAgA">8.8</td>
<td id="mwAgE">20.2</td>
<td align="left" id="mwAgI"><a href="https://en.wikipedia.org/wiki/Airline" id="mwAgM" rel="mw:WikiLink" title="Airline">Airline</a></td></tr>
<tr id="mwAgQ">
<td id="mwAgU">43</td>
<td id="mwAgY">1219</td>
<td align="left" id="mwAgc"><a href="https://en.wikipedia.org/wiki/Adani_Ports_&amp;_SEZ" id="mwAgg" rel="mw:WikiLink" title="Adani Ports &amp; SEZ">Adani Ports &amp; SEZ</a></td>
<td align="left" id="mwAgk">Ahmedabad</td>
<td id="mwAgo">3.2</td>
<td id="mwAgs">1.0</td>
<td id="mwAgw">14.3</td>
<td id="mwAg0">34.6</td>
<td align="left" id="mwAg4"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Shipping" id="mwAg8" rel="mw:WikiLink" title="Shipping">Shipping</a></td></tr>
<tr id="mwAhA">
<td id="mwAhE">44</td>
<td id="mwAhI">1259</td>
<td align="left" id="mwAhM"><a href="https://en.wikipedia.org/wiki/IDBI_Bank" id="mwAhQ" rel="mw:WikiLink" title="IDBI Bank">IDBI Bank</a></td>
<td align="left" id="mwAhU">Mumbai</td>
<td id="mwAhY">3.7</td>
<td id="mwAhc">0.7</td>
<td id="mwAhg">43.7</td>
<td id="mwAhk">10.9</td>
<td align="left" id="mwAho">Banking</td></tr>
<tr id="mwAhs">
<td id="mwAhw">45</td>
<td id="mwAh0">1264</td>
<td align="left" id="mwAh4"><a href="https://en.wikipedia.org/wiki/Bajaj_Auto" id="mwAh8" rel="mw:WikiLink" title="Bajaj Auto">Bajaj Auto</a></td>
<td align="left" id="mwAiA">Pune</td>
<td id="mwAiE">5.4</td>
<td id="mwAiI">0.9</td>
<td id="mwAiM">4.7</td>
<td id="mwAiQ">29.4</td>

In [7]:
table = soup.find_all('table')[0]
print(table)

<table class="wikitable sortable" id="mwHw" style="text-align:right;">
<tbody id="mwIA"><tr id="mwIQ"><th align="center" id="mwIg">Rank</th>
<th align="center" id="mwIw">Forbes<br id="mwJA"/> 2000 rank</th>
<th align="center" id="mwJQ">Name</th>
<th align="center" id="mwJg">Headquarters</th>
<th align="center" id="mwJw">Revenue<br id="mwKA"/>(billions US$)</th>
<th align="center" id="mwKQ">Profit<br id="mwKg"/>(billions US$)</th>
<th align="center" id="mwKw">Assets<br id="mwLA"/>(billions US$)</th>
<th align="center" id="mwLQ">Value<br id="mwLg"/>(billions US$)</th>
<th align="center" id="mwLw">Industry</th></tr>
<tr id="mwMA">
<td id="mwMQ">1</td>
<td id="mwMg">49</td>
<td align="left" id="mwMw"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Reliance_Industries_Limited" id="mwNA" rel="mw:WikiLink" title="Reliance Industries Limited">Reliance Industries Limited</a></td>
<td align="left" id="mwNQ">Mumbai</td>
<td id="mwNg">108.8</td>
<td id="mwNw">8.4</td>
<td id="mwOA">210.5</td>
<td id="mwOQ">233.1</td>
<td align="left" id="mwOg"><a href="https://en.wikipedia.org/wiki/Conglomerate_(company)" id="mwOw" rel="mw:WikiLink" title="Conglomerate (company)">Conglomerate</a></td></tr>
<tr id="mwPA">
<td id="mwPQ">2</td>
<td id="mwPg">55</td>
<td align="left" id="mwPw"><a href="https://en.wikipedia.org/wiki/State_Bank_of_India" id="mwQA" rel="mw:WikiLink" title="State Bank of India">State Bank of India</a></td>
<td align="left" id="mwQQ">Mumbai</td>
<td id="mwQg">71.8</td>
<td id="mwQw">8.1</td>
<td id="mwRA">807.4</td>
<td id="mwRQ">87.6</td>
<td align="left" id="mwRg">Banking</td></tr>
<tr id="mwRw">
<td id="mwSA">3</td>
<td id="mwSQ">65</td>
<td align="left" id="mwSg"><a href="https://en.wikipedia.org/wiki/HDFC_Bank" id="mwSw" rel="mw:WikiLink" title="HDFC Bank">HDFC Bank</a></td>
<td align="left" id="mwTA">Mumbai</td>
<td id="mwTQ">49.3</td>
<td id="mwTg">7.7</td>
<td id="mwTw">483.2</td>
<td id="mwUA">133.6</td>
<td align="left" id="mwUQ">Banking</td></tr>
<tr id="mwUg">
<td id="mwUw">4</td>
<td id="mwVA">70</td>
<td align="left" id="mwVQ"><a href="https://en.wikipedia.org/wiki/Life_Insurance_Corporation" id="mwVg" rel="mw:WikiLink" title="Life Insurance Corporation">Life Insurance Corporation</a></td>
<td align="left" id="mwVw">New Delhi</td>
<td id="mwWA">98.0</td>
<td id="mwWQ">4.9</td>
<td id="mwWg">561.4</td>
<td id="mwWw">73.6</td>
<td align="left" id="mwXA">Insurance</td></tr>
<tr id="mwXQ">
<td id="mwXg">5</td>
<td id="mwXw">142</td>
<td align="left" id="mwYA"><a href="https://en.wikipedia.org/wiki/ICICI_Bank" id="mwYQ" rel="mw:WikiLink" title="ICICI Bank">ICICI Bank</a></td>
<td align="left" id="mwYg">Mumbai</td>
<td id="mwYw">28.5</td>
<td id="mwZA">5.3</td>
<td id="mwZQ">283.5</td>
<td id="mwZg">95.3</td>
<td align="left" id="mwZw">Banking</td></tr>
<tr id="mwaA">
<td id="mwaQ">6</td>
<td id="mwag">207</td>
<td align="left" id="mwaw"><a href="https://en.wikipedia.org/wiki/Oil_and_Natural_Gas_Corporation" id="mwbA" rel="mw:WikiLink" title="Oil and Natural Gas Corporation">Oil and Natural Gas Corporation</a></td>
<td align="left" id="mwbQ">New Delhi</td>
<td id="mwbg">77.5</td>
<td id="mwbw">5.1</td>
<td id="mwcA">80.6</td>
<td id="mwcQ">41.9</td>
<td align="left" id="mwcg">Oil and gas</td></tr>
<tr id="mwcw">
<td id="mwdA">7</td>
<td id="mwdQ">259</td>
<td align="left" id="mwdg"><a href="https://en.wikipedia.org/wiki/Indian_Oil_Corporation" id="mwdw" rel="mw:WikiLink" title="Indian Oil Corporation">Indian Oil Corporation</a></td>
<td align="left" id="mweA">New Delhi</td>
<td id="mweQ">93.8</td>
<td id="mweg">5.0</td>
<td id="mwew">57.8</td>
<td id="mwfA">27.8</td>
<td align="left" id="mwfQ"><a href="https://en.wikipedia.org/wiki/Petroleum_industry" id="mwfg" rel="mw:WikiLink" title="Petroleum industry">Oil and gas</a></td></tr>
<tr id="mwfw">
<td id="mwgA">8</td>
<td id="mwgQ">284</td>
<td align="left" id="mwgg"><a href="https://en.wikipedia.org/wiki/Tata_Motors" id="mwgw" rel="mw:WikiLink" title="Tata Motors">Tata Motors</a></td>
<td align="left" id="mwhA">Mumbai</td>
<td id="mwhQ">52.9</td>
<td id="mwhg">3.8</td>
<td id="mwhw">44.4</td>
<td id="mwiA">43.8</td>
<td align="left" id="mwiQ">Automotive</td></tr>
<tr id="mwig">
<td id="mwiw">9</td>
<td id="mwjA">293</td>
<td align="left" id="mwjQ"><a href="https://en.wikipedia.org/wiki/Axis_Bank" id="mwjg" rel="mw:WikiLink" title="Axis Bank">Axis Bank</a></td>
<td align="left" id="mwjw">Mumbai</td>
<td id="mwkA">16.7</td>
<td id="mwkQ">3.2</td>
<td id="mwkg">182.0</td>
<td id="mwkw">42.3</td>
<td align="left" id="mwlA">Banking</td></tr>
<tr id="mwlQ">
<td id="mwlg">10</td>
<td id="mwlw">372</td>
<td align="left" id="mwmA"><a href="https://en.wikipedia.org/wiki/NTPC_Limited" id="mwmQ" rel="mw:WikiLink" title="NTPC Limited">NTPC Limited</a></td>
<td align="left" id="mwmg">New Delhi</td>
<td id="mwmw">21.2</td>
<td id="mwnA">2.4</td>
<td id="mwnQ">54.7</td>
<td id="mwng">42.5</td>
<td align="left" id="mwnw">Utilities</td></tr>
<tr id="mwoA">
<td id="mwoQ">11</td>
<td id="mwog">398</td>
<td align="left" id="mwow"><a href="https://en.wikipedia.org/wiki/Larsen_&amp;_Toubro" id="mwpA" rel="mw:WikiLink" title="Larsen &amp; Toubro">Larsen &amp; Toubro</a></td>
<td align="left" id="mwpQ">Mumbai</td>
<td id="mwpg">26.7</td>
<td id="mwpw">1.6</td>
<td id="mwqA">40.7</td>
<td id="mwqQ">56.9</td>
<td align="left" id="mwqg">Capital goods</td></tr>
<tr id="mwqw">
<td id="mwrA">12</td>
<td id="mwrQ">412</td>
<td align="left" id="mwrg"><a href="https://en.wikipedia.org/wiki/Tata_Consultancy_Services" id="mwrw" rel="mw:WikiLink" title="Tata Consultancy Services">Tata Consultancy Services</a></td>
<td align="left" id="mwsA">Mumbai</td>
<td id="mwsQ">29.1</td>
<td id="mwsg">5.5</td>
<td id="mwsw">17.6</td>
<td id="mwtA">166.5</td>
<td align="left" id="mwtQ">Infotech</td></tr>
<tr id="mwtg">
<td id="mwtw">13</td>
<td id="mwuA">440</td>
<td align="left" id="mwuQ"><a href="https://en.wikipedia.org/wiki/Bank_of_Baroda" id="mwug" rel="mw:WikiLink" title="Bank of Baroda">Bank of Baroda</a></td>
<td align="left" id="mwuw">Vadodara</td>
<td id="mwvA">17.1</td>
<td id="mwvQ">2.3</td>
<td id="mwvg">198.4</td>
<td id="mwvw">16.2</td>
<td align="left" id="mwwA">Banking</td></tr>
<tr id="mwwQ">
<td id="mwwg">14</td>
<td id="mwww">442</td>
<td align="left" id="mwxA"><a href="https://en.wikipedia.org/wiki/Kotak_Mahindra_Bank" id="mwxQ" rel="mw:WikiLink" title="Kotak Mahindra Bank">Kotak Mahindra Bank</a></td>
<td align="left" id="mwxg">Mumbai</td>
<td id="mwxw">11.4</td>
<td id="mwyA">2.2</td>
<td id="mwyQ">92.0</td>
<td id="mwyg">40.5</td>
<td align="left" id="mwyw">Banking</td></tr>
<tr id="mwzA">
<td id="mwzQ">15</td>
<td id="mwzg">472</td>
<td align="left" id="mwzw"><a href="https://en.wikipedia.org/wiki/Bharti_Airtel" id="mw0A" rel="mw:WikiLink" title="Bharti Airtel">Bharti Airtel</a></td>
<td align="left" id="mw0Q">New Delhi</td>
<td id="mw0g">18.1</td>
<td id="mw0w">0.9</td>
<td id="mw1A">53.3</td>
<td id="mw1Q">91.5</td>
<td align="left" id="mw1g">Telecommunication</td></tr>
<tr id="mw1w">
<td id="mw2A">16</td>
<td id="mw2Q">488</td>
<td align="left" id="mw2g"><a href="https://en.wikipedia.org/wiki/Coal_India" id="mw2w" rel="mw:WikiLink" title="Coal India">Coal India</a></td>
<td align="left" id="mw3A">Kolkata</td>
<td id="mw3Q">17.2</td>
<td id="mw3g">3.9</td>
<td id="mw3w">28.5</td>
<td id="mw4A">34.8</td>
<td align="left" id="mw4Q">Metals and mining</td></tr>
<tr id="mw4g">
<td id="mw4w">17</td>
<td id="mw5A">525</td>
<td align="left" id="mw5Q"><a href="https://en.wikipedia.org/wiki/Canara_Bank" id="mw5g" rel="mw:WikiLink" title="Canara Bank">Canara Bank</a></td>
<td align="left" id="mw5w">Bangalore</td>
<td id="mw6A">16.8</td>
<td id="mw6Q">1.8</td>
<td id="mw6g">184.0</td>
<td id="mw6w">12.4</td>
<td align="left" id="mw7A">Banking</td></tr>
<tr id="mw7Q">
<td id="mw7g">18</td>
<td id="mw7w">533</td>
<td align="left" id="mw8A"><a href="https://en.wikipedia.org/wiki/Power_Finance_Corporation" id="mw8Q" rel="mw:WikiLink" title="Power Finance Corporation">Power Finance Corporation</a></td>
<td align="left" id="mw8g">New Delhi</td>
<td id="mw8w">11.1</td>
<td id="mw9A">2.4</td>
<td id="mw9Q">124.6</td>
<td id="mw9g">18.5</td>
<td align="left" id="mw9w">Financials</td></tr>
<tr id="mw-A">
<td id="mw-Q">19</td>
<td id="mw-g">537</td>
<td align="left" id="mw-w"><a href="https://en.wikipedia.org/wiki/Bharat_Petroleum" id="mw_A" rel="mw:WikiLink" title="Bharat Petroleum">Bharat Petroleum</a></td>
<td align="left" id="mw_Q">Mumbai</td>
<td id="mw_g">54.1</td>
<td id="mw_w">3.2</td>
<td id="mwAQA">24.3</td>
<td id="mwAQE">16.4</td>
<td align="left" id="mwAQI">Oil and gas</td></tr>
<tr id="mwAQM">
<td id="mwAQQ">20</td>
<td id="mwAQU">569</td>
<td align="left" id="mwAQY"><a href="https://en.wikipedia.org/wiki/Infosys" id="mwAQc" rel="mw:WikiLink" title="Infosys">Infosys</a></td>
<td align="left" id="mwAQg">Bangalore</td>
<td id="mwAQk">18.6</td>
<td id="mwAQo">3.2</td>
<td id="mwAQs">16.5</td>
<td id="mwAQw">71.9</td>
<td align="left" id="mwAQ0">Infotech</td></tr>
<tr id="mwAQ4">
<td id="mwAQ8">21</td>
<td id="mwARA">571</td>
<td align="left" id="mwARE"><a href="https://en.wikipedia.org/wiki/Punjab_National_Bank" id="mwARI" rel="mw:WikiLink" title="Punjab National Bank">Punjab National Bank</a></td>
<td align="left" id="mwARM">New Delhi</td>
<td id="mwARQ">14.8</td>
<td id="mwARU">1.1</td>
<td id="mwARY">191.7</td>
<td id="mwARc">16.5</td>
<td align="left" id="mwARg">Banking</td></tr>
<tr id="mwARk">
<td id="mwARo">22</td>
<td id="mwARs">575</td>
<td align="left" id="mwARw"><a href="https://en.wikipedia.org/wiki/Union_Bank_of_India" id="mwAR0" rel="mw:WikiLink" title="Union Bank of India">Union Bank of India</a></td>
<td align="left" id="mwAR4">Mumbai</td>
<td id="mwAR8">14.3</td>
<td id="mwASA">1.7</td>
<td id="mwASE">168.1</td>
<td id="mwASI">12.7</td>
<td align="left" id="mwASM">Banking</td></tr>
<tr id="mwASQ">
<td id="mwASU">23</td>
<td id="mwASY">592</td>
<td align="left" id="mwASc"><a href="https://en.wikipedia.org/wiki/Bajaj_Finserv" id="mwASg" rel="mw:WikiLink" title="Bajaj Finserv">Bajaj Finserv</a></td>
<td align="left" id="mwASk">Pune</td>
<td id="mwASo">13.0</td>
<td id="mwASs">1.0</td>
<td id="mwASw">64.5</td>
<td id="mwAS0">30.3</td>
<td align="left" id="mwAS4">Financials</td></tr>
<tr id="mwAS8">
<td id="mwATA">24</td>
<td id="mwATE">593</td>
<td align="left" id="mwATI"><a href="https://en.wikipedia.org/wiki/Mahindra_&amp;_Mahindra" id="mwATM" rel="mw:WikiLink" title="Mahindra &amp; Mahindra">Mahindra &amp; Mahindra</a></td>
<td align="left" id="mwATQ">Mumbai</td>
<td id="mwATU">16.8</td>
<td id="mwATY">1.4</td>
<td id="mwATc">28.3</td>
<td id="mwATg">37.5</td>
<td align="left" id="mwATk">Automotive</td></tr>
<tr id="mwATo">
<td id="mwATs">25</td>
<td id="mwATw">645</td>
<td align="left" id="mwAT0"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/JSW_Steel_Ltd" id="mwAT4" rel="mw:WikiLink" title="JSW Steel Ltd">JSW Steel Ltd</a></td>
<td align="left" id="mwAT8">Mumbai</td>
<td id="mwAUA">21.1</td>
<td id="mwAUE">1.1</td>
<td id="mwAUI">27.4</td>
<td id="mwAUM">26.6</td>
<td align="left" id="mwAUQ">Iron and steel</td></tr>
<tr id="mwAUU">
<td id="mwAUY">26</td>
<td id="mwAUc">684</td>
<td align="left" id="mwAUg"><a href="https://en.wikipedia.org/wiki/Hindalco_Industries" id="mwAUk" rel="mw:WikiLink" title="Hindalco Industries">Hindalco Industries</a></td>
<td align="left" id="mwAUo">Mumbai</td>
<td id="mwAUs">26.1</td>
<td id="mwAUw">1.1</td>
<td id="mwAU0">27.1</td>
<td id="mwAU4">17.7</td>
<td align="left" id="mwAU8">Metals and mining</td></tr>
<tr id="mwAVA">
<td id="mwAVE">27</td>
<td id="mwAVI">746</td>
<td align="left" id="mwAVM"><a href="https://en.wikipedia.org/wiki/Grasim_Industries" id="mwAVQ" rel="mw:WikiLink" title="Grasim Industries">Grasim Industries</a></td>
<td align="left" id="mwAVU">Mumbai</td>
<td id="mwAVY">15.3</td>
<td id="mwAVc">0.7</td>
<td id="mwAVg">47.0</td>
<td id="mwAVk">19.8</td>
<td align="left" id="mwAVo">Diversified</td></tr>
<tr id="mwAVs">
<td id="mwAVw">28</td>
<td id="mwAV0">764</td>
<td align="left" id="mwAV4"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/HCL_Technologies" id="mwAV8" rel="mw:WikiLink" title="HCL Technologies">HCL Technologies</a></td>
<td align="left" id="mwAWA">Noida</td>
<td id="mwAWE">13.3</td>
<td id="mwAWI">1.9</td>
<td id="mwAWM">12.0</td>
<td id="mwAWQ">43.4</td>
<td align="left" id="mwAWU">Infotech</td></tr>
<tr id="mwAWY">
<td id="mwAWc">29</td>
<td id="mwAWg">810</td>
<td align="left" id="mwAWk"><a href="https://en.wikipedia.org/wiki/ITC_Limited" id="mwAWo" rel="mw:WikiLink" title="ITC Limited">ITC Limited</a></td>
<td align="left" id="mwAWs">Kolkata</td>
<td id="mwAWw">8.5</td>
<td id="mwAW0">2.5</td>
<td id="mwAW4">10.5</td>
<td id="mwAW8">65.4</td>
<td align="left" id="mwAXA">Consumer goods</td></tr>
<tr id="mwAXE">
<td id="mwAXI">30</td>
<td id="mwAXM">827</td>
<td align="left" id="mwAXQ"><a href="https://en.wikipedia.org/wiki/Power_Grid_Corporation_of_India" id="mwAXU" rel="mw:WikiLink" title="Power Grid Corporation of India">Power Grid Corporation of India</a></td>
<td align="left" id="mwAXY">Gurgaon</td>
<td id="mwAXc">5.6</td>
<td id="mwAXg">1.9</td>
<td id="mwAXk">29.6</td>
<td id="mwAXo">35.0</td>
<td align="left" id="mwAXs">Utilities</td></tr>
<tr id="mwAXw">
<td id="mwAX0">31</td>
<td id="mwAX4">834</td>
<td align="left" id="mwAX8"><a href="https://en.wikipedia.org/wiki/Tata_Steel" id="mwAYA" rel="mw:WikiLink" title="Tata Steel">Tata Steel</a></td>
<td align="left" id="mwAYE">Kolkata</td>
<td id="mwAYI">28.3</td>
<td id="mwAYM">−0.4</td>
<td id="mwAYQ">32.7</td>
<td id="mwAYU">25.1</td>
<td align="left" id="mwAYY">Iron and steel</td></tr>
<tr id="mwAYc">
<td id="mwAYg">32</td>
<td id="mwAYk">901</td>
<td align="left" id="mwAYo"><a href="https://en.wikipedia.org/wiki/IndusInd_Bank" id="mwAYs" rel="mw:WikiLink" title="IndusInd Bank">IndusInd Bank</a></td>
<td align="left" id="mwAYw">Mumbai</td>
<td id="mwAY0">6.7</td>
<td id="mwAY4">1.1</td>
<td id="mwAY8">61.8</td>
<td id="mwAZA">13.2</td>
<td align="left" id="mwAZE">Banking</td></tr>
<tr id="mwAZI">
<td id="mwAZM">33</td>
<td id="mwAZQ">922</td>
<td align="left" id="mwAZU"><a href="https://en.wikipedia.org/wiki/Indian_Railway_Finance_Corporation" id="mwAZY" rel="mw:WikiLink" title="Indian Railway Finance Corporation">Indian Railway Finance Corporation</a></td>
<td align="left" id="mwAZc">New Delhi</td>
<td id="mwAZg">3.2</td>
<td id="mwAZk">0.7</td>
<td id="mwAZo">58.6</td>
<td id="mwAZs">26.5</td>
<td align="left" id="mwAZw">Financials</td></tr>
<tr id="mwAZ0">
<td id="mwAZ4">34</td>
<td id="mwAZ8">926</td>
<td align="left" id="mwAaA"><a href="https://en.wikipedia.org/wiki/Wipro" id="mwAaE" rel="mw:WikiLink" title="Wipro">Wipro</a></td>
<td align="left" id="mwAaI">Bangalore</td>
<td id="mwAaM">10.8</td>
<td id="mwAaQ">1.3</td>
<td id="mwAaU">13.8</td>
<td id="mwAaY">28.9</td>
<td align="left" id="mwAac">Infotech</td></tr>
<tr id="mwAag">
<td id="mwAak">35</td>
<td id="mwAao">930</td>
<td align="left" id="mwAas"><a href="https://en.wikipedia.org/wiki/GAIL" id="mwAaw" rel="mw:WikiLink" title="GAIL">GAIL</a></td>
<td align="left" id="mwAa0">New Delhi</td>
<td id="mwAa4">16.1</td>
<td id="mwAa8">1.2</td>
<td id="mwAbA">15.0</td>
<td id="mwAbE">16.1</td>
<td align="left" id="mwAbI">Oil and gas</td></tr>
<tr id="mwAbM">
<td id="mwAbQ">36</td>
<td id="mwAbU">947</td>
<td align="left" id="mwAbY"><a href="https://en.wikipedia.org/wiki/Indian_Bank" id="mwAbc" rel="mw:WikiLink" title="Indian Bank">Indian Bank</a></td>
<td align="left" id="mwAbg">Chennai</td>
<td id="mwAbk">7.8</td>
<td id="mwAbo">1.0</td>
<td id="mwAbs">95.4</td>
<td id="mwAbw">8.7</td>
<td align="left" id="mwAb0">Banking</td></tr>
<tr id="mwAb4">
<td id="mwAb8">37</td>
<td id="mwAcA">961</td>
<td align="left" id="mwAcE"><a href="https://en.wikipedia.org/wiki/Vedanta_Limited" id="mwAcI" rel="mw:WikiLink" title="Vedanta Limited">Vedanta Limited</a></td>
<td align="left" id="mwAcM">Mumbai</td>
<td id="mwAcQ">17.4</td>
<td id="mwAcU">0.5</td>
<td id="mwAcY">22.9</td>
<td id="mwAcc">19.7</td>
<td align="left" id="mwAcg">Metals and mining</td></tr>
<tr id="mwAck">
<td id="mwAco">38</td>
<td id="mwAcs">1048</td>
<td align="left" id="mwAcw"><a href="https://en.wikipedia.org/wiki/Adani_Power" id="mwAc0" rel="mw:WikiLink" title="Adani Power">Adani Power</a></td>
<td align="left" id="mwAc4"><a href="https://en.wikipedia.org/wiki/Ahmedabad" id="mwAc8" rel="mw:WikiLink" title="Ahmedabad">Ahmedabad</a></td>
<td id="mwAdA">6.1</td>
<td id="mwAdE">2.5</td>
<td id="mwAdI">11.1</td>
<td id="mwAdM">29.4</td>
<td align="left" id="mwAdQ"><a href="https://en.wikipedia.org/wiki/Energy" id="mwAdU" rel="mw:WikiLink" title="Energy">Energy</a></td></tr>
<tr id="mwAdY">
<td id="mwAdc">39</td>
<td id="mwAdg">1053</td>
<td align="left" id="mwAdk"><a href="https://en.wikipedia.org/wiki/Bank_of_India" id="mwAdo" rel="mw:WikiLink" title="Bank of India">Bank of India</a></td>
<td align="left" id="mwAds">Mumbai</td>
<td id="mwAdw">8.1</td>
<td id="mwAd0">0.8</td>
<td id="mwAd4">110.8</td>
<td id="mwAd8">6.7</td>
<td align="left" id="mwAeA">Banking</td></tr>
<tr id="mwAeE">
<td id="mwAeI">40</td>
<td id="mwAeM">1059</td>
<td align="left" id="mwAeQ"><a href="https://en.wikipedia.org/wiki/Adani_Enterprises" id="mwAeU" rel="mw:WikiLink" title="Adani Enterprises">Adani Enterprises</a></td>
<td align="left" id="mwAeY">Ahmedabad</td>
<td id="mwAec">12.7</td>
<td id="mwAeg">0.4</td>
<td id="mwAek">19.3</td>
<td id="mwAeo">41.9</td>
<td align="left" id="mwAes">Holding</td></tr>
<tr id="mwAew">
<td id="mwAe0">41</td>
<td id="mwAe4">1161</td>
<td align="left" id="mwAe8"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Sun_Pharmaceutical" id="mwAfA" rel="mw:WikiLink" title="Sun Pharmaceutical">Sun Pharmaceutical</a></td>
<td align="left" id="mwAfE">Mumbai</td>
<td id="mwAfI">5.7</td>
<td id="mwAfM">1.1</td>
<td id="mwAfQ">9.6</td>
<td id="mwAfU">44.1</td>
<td align="left" id="mwAfY"><a href="https://en.wikipedia.org/wiki/Pharmaceutical_industry" id="mwAfc" rel="mw:WikiLink" title="Pharmaceutical industry">Pharmaceuticals</a></td></tr>
<tr id="mwAfg">
<td id="mwAfk">42</td>
<td id="mwAfo">1212</td>
<td align="left" id="mwAfs"><a href="https://en.wikipedia.org/wiki/IndiGo" id="mwAfw" rel="mw:WikiLink" title="IndiGo">IndiGo</a></td>
<td align="left" id="mwAf0">Gurgaon</td>
<td id="mwAf4">7.9</td>
<td id="mwAf8">0.9</td>
<td id="mwAgA">8.8</td>
<td id="mwAgE">20.2</td>
<td align="left" id="mwAgI"><a href="https://en.wikipedia.org/wiki/Airline" id="mwAgM" rel="mw:WikiLink" title="Airline">Airline</a></td></tr>
<tr id="mwAgQ">
<td id="mwAgU">43</td>
<td id="mwAgY">1219</td>
<td align="left" id="mwAgc"><a href="https://en.wikipedia.org/wiki/Adani_Ports_&amp;_SEZ" id="mwAgg" rel="mw:WikiLink" title="Adani Ports &amp; SEZ">Adani Ports &amp; SEZ</a></td>
<td align="left" id="mwAgk">Ahmedabad</td>
<td id="mwAgo">3.2</td>
<td id="mwAgs">1.0</td>
<td id="mwAgw">14.3</td>
<td id="mwAg0">34.6</td>
<td align="left" id="mwAg4"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Shipping" id="mwAg8" rel="mw:WikiLink" title="Shipping">Shipping</a></td></tr>
<tr id="mwAhA">
<td id="mwAhE">44</td>
<td id="mwAhI">1259</td>
<td align="left" id="mwAhM"><a href="https://en.wikipedia.org/wiki/IDBI_Bank" id="mwAhQ" rel="mw:WikiLink" title="IDBI Bank">IDBI Bank</a></td>
<td align="left" id="mwAhU">Mumbai</td>
<td id="mwAhY">3.7</td>
<td id="mwAhc">0.7</td>
<td id="mwAhg">43.7</td>
<td id="mwAhk">10.9</td>
<td align="left" id="mwAho">Banking</td></tr>
<tr id="mwAhs">
<td id="mwAhw">45</td>
<td id="mwAh0">1264</td>
<td align="left" id="mwAh4"><a href="https://en.wikipedia.org/wiki/Bajaj_Auto" id="mwAh8" rel="mw:WikiLink" title="Bajaj Auto">Bajaj Auto</a></td>
<td align="left" id="mwAiA">Pune</td>
<td id="mwAiE">5.4</td>
<td id="mwAiI">0.9</td>
<td id="mwAiM">4.7</td>
<td id="mwAiQ">29.4</td>

In [8]:
titles = table.find_all('th')

In [9]:
titles

[<th align="center" id="mwIg">Rank</th>,
 <th align="center" id="mwIw">Forbes<br id="mwJA"/> 2000 rank</th>,
 <th align="center" id="mwJQ">Name</th>,
 <th align="center" id="mwJg">Headquarters</th>,
 <th align="center" id="mwJw">Revenue<br id="mwKA"/>(billions US$)</th>,
 <th align="center" id="mwKQ">Profit<br id="mwKg"/>(billions US$)</th>,
 <th align="center" id="mwKw">Assets<br id="mwLA"/>(billions US$)</th>,
 <th align="center" id="mwLQ">Value<br id="mwLg"/>(billions US$)</th>,
 <th align="center" id="mwLw">Industry</th>]

In [10]:
table_titles = [title.text for title in titles] 
print(table_titles)

['Rank', 'Forbes 2000 rank', 'Name', 'Headquarters', 'Revenue(billions US$)', 'Profit(billions US$)', 'Assets(billions US$)', 'Value(billions US$)', 'Industry']

In [11]:
import pandas as pd

In [12]:
df = pd.DataFrame(columns = table_titles)
df

Empty DataFrame
Columns: [Rank, Forbes 2000 rank, Name, Headquarters, Revenue(billions US$), Profit(billions US$), Assets(billions US$), Value(billions US$), Industry]
Index: []

In [14]:
column_data = table.find_all('tr')
column_data

[<tr id="mwIQ"><th align="center" id="mwIg">Rank</th>
 <th align="center" id="mwIw">Forbes<br id="mwJA"/> 2000 rank</th>
 <th align="center" id="mwJQ">Name</th>
 <th align="center" id="mwJg">Headquarters</th>
 <th align="center" id="mwJw">Revenue<br id="mwKA"/>(billions US$)</th>
 <th align="center" id="mwKQ">Profit<br id="mwKg"/>(billions US$)</th>
 <th align="center" id="mwKw">Assets<br id="mwLA"/>(billions US$)</th>
 <th align="center" id="mwLQ">Value<br id="mwLg"/>(billions US$)</th>
 <th align="center" id="mwLw">Industry</th></tr>,
 <tr id="mwMA">
 <td id="mwMQ">1</td>
 <td id="mwMg">49</td>
 <td align="left" id="mwMw"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Reliance_Industries_Limited" id="mwNA" rel="mw:WikiLink" title="Reliance Industries Limited">Reliance Industries Limited</a></td>
 <td align="left" id="mwNQ">Mumbai</td>
 <td id="mwNg">108.8</td>
 <td id="mwNw">8.4</td>
 <td id="mwOA">210.5</td>
 <td id="mwOQ">233.1</td>
 <td align="left" id="mwOg"><a href="https://en.wikipedia.org/wiki/Conglomerate_(company)" id="mwOw" rel="mw:WikiLink" title="Conglomerate (company)">Conglomerate</a></td></tr>,
 <tr id="mwPA">
 <td id="mwPQ">2</td>
 <td id="mwPg">55</td>
 <td align="left" id="mwPw"><a href="https://en.wikipedia.org/wiki/State_Bank_of_India" id="mwQA" rel="mw:WikiLink" title="State Bank of India">State Bank of India</a></td>
 <td align="left" id="mwQQ">Mumbai</td>
 <td id="mwQg">71.8</td>
 <td id="mwQw">8.1</td>
 <td id="mwRA">807.4</td>
 <td id="mwRQ">87.6</td>
 <td align="left" id="mwRg">Banking</td></tr>,
 <tr id="mwRw">
 <td id="mwSA">3</td>
 <td id="mwSQ">65</td>
 <td align="left" id="mwSg"><a href="https://en.wikipedia.org/wiki/HDFC_Bank" id="mwSw" rel="mw:WikiLink" title="HDFC Bank">HDFC Bank</a></td>
 <td align="left" id="mwTA">Mumbai</td>
 <td id="mwTQ">49.3</td>
 <td id="mwTg">7.7</td>
 <td id="mwTw">483.2</td>
 <td id="mwUA">133.6</td>
 <td align="left" id="mwUQ">Banking</td></tr>,
 <tr id="mwUg">
 <td id="mwUw">4</td>
 <td id="mwVA">70</td>
 <td align="left" id="mwVQ"><a href="https://en.wikipedia.org/wiki/Life_Insurance_Corporation" id="mwVg" rel="mw:WikiLink" title="Life Insurance Corporation">Life Insurance Corporation</a></td>
 <td align="left" id="mwVw">New Delhi</td>
 <td id="mwWA">98.0</td>
 <td id="mwWQ">4.9</td>
 <td id="mwWg">561.4</td>
 <td id="mwWw">73.6</td>
 <td align="left" id="mwXA">Insurance</td></tr>,
 <tr id="mwXQ">
 <td id="mwXg">5</td>
 <td id="mwXw">142</td>
 <td align="left" id="mwYA"><a href="https://en.wikipedia.org/wiki/ICICI_Bank" id="mwYQ" rel="mw:WikiLink" title="ICICI Bank">ICICI Bank</a></td>
 <td align="left" id="mwYg">Mumbai</td>
 <td id="mwYw">28.5</td>
 <td id="mwZA">5.3</td>
 <td id="mwZQ">283.5</td>
 <td id="mwZg">95.3</td>
 <td align="left" id="mwZw">Banking</td></tr>,
 <tr id="mwaA">
 <td id="mwaQ">6</td>
 <td id="mwag">207</td>
 <td align="left" id="mwaw"><a href="https://en.wikipedia.org/wiki/Oil_and_Natural_Gas_Corporation" id="mwbA" rel="mw:WikiLink" title="Oil and Natural Gas Corporation">Oil and Natural Gas Corporation</a></td>
 <td align="left" id="mwbQ">New Delhi</td>
 <td id="mwbg">77.5</td>
 <td id="mwbw">5.1</td>
 <td id="mwcA">80.6</td>
 <td id="mwcQ">41.9</td>
 <td align="left" id="mwcg">Oil and gas</td></tr>,
 <tr id="mwcw">
 <td id="mwdA">7</td>
 <td id="mwdQ">259</td>
 <td align="left" id="mwdg"><a href="https://en.wikipedia.org/wiki/Indian_Oil_Corporation" id="mwdw" rel="mw:WikiLink" title="Indian Oil Corporation">Indian Oil Corporation</a></td>
 <td align="left" id="mweA">New Delhi</td>
 <td id="mweQ">93.8</td>
 <td id="mweg">5.0</td>
 <td id="mwew">57.8</td>
 <td id="mwfA">27.8</td>
 <td align="left" id="mwfQ"><a href="https://en.wikipedia.org/wiki/Petroleum_industry" id="mwfg" rel="mw:WikiLink" title="Petroleum industry">Oil and gas</a></td></tr>,
 <tr id="mwfw">
 <td id="mwgA">8</td>
 <td id="mwgQ">284</td>
 <td align="left" id="mwgg"><a href="https://en.wikipedia.org/wiki/Tata_Motors" id="mwgw" rel="mw:WikiLink" title="Tata Motors">Tata Motors</a></td>
 <td align="left" id="mwhA">Mumbai</td>
 <td id="mwhQ">52.9</td>
 <td id="mwhg">3.8</td>
 <td id="mwhw">44.4</td>
 <td id="mwiA">43.8</td>
 <td align="left" id="mwiQ">Automotive</td></tr>,
 <tr id="mwig">
 <td id="mwiw">9</td>
 <td id="mwjA">293</td>
 <td align="left" id="mwjQ"><a href="https://en.wikipedia.org/wiki/Axis_Bank" id="mwjg" rel="mw:WikiLink" title="Axis Bank">Axis Bank</a></td>
 <td align="left" id="mwjw">Mumbai</td>
 <td id="mwkA">16.7</td>
 <td id="mwkQ">3.2</td>
 <td id="mwkg">182.0</td>
 <td id="mwkw">42.3</td>
 <td align="left" id="mwlA">Banking</td></tr>,
 <tr id="mwlQ">
 <td id="mwlg">10</td>
 <td id="mwlw">372</td>
 <td align="left" id="mwmA"><a href="https://en.wikipedia.org/wiki/NTPC_Limited" id="mwmQ" rel="mw:WikiLink" title="NTPC Limited">NTPC Limited</a></td>
 <td align="left" id="mwmg">New Delhi</td>
 <td id="mwmw">21.2</td>
 <td id="mwnA">2.4</td>
 <td id="mwnQ">54.7</td>
 <td id="mwng">42.5</td>
 <td align="left" id="mwnw">Utilities</td></tr>,
 <tr id="mwoA">
 <td id="mwoQ">11</td>
 <td id="mwog">398</td>
 <td align="left" id="mwow"><a href="https://en.wikipedia.org/wiki/Larsen_&amp;_Toubro" id="mwpA" rel="mw:WikiLink" title="Larsen &amp; Toubro">Larsen &amp; Toubro</a></td>
 <td align="left" id="mwpQ">Mumbai</td>
 <td id="mwpg">26.7</td>
 <td id="mwpw">1.6</td>
 <td id="mwqA">40.7</td>
 <td id="mwqQ">56.9</td>
 <td align="left" id="mwqg">Capital goods</td></tr>,
 <tr id="mwqw">
 <td id="mwrA">12</td>
 <td id="mwrQ">412</td>
 <td align="left" id="mwrg"><a href="https://en.wikipedia.org/wiki/Tata_Consultancy_Services" id="mwrw" rel="mw:WikiLink" title="Tata Consultancy Services">Tata Consultancy Services</a></td>
 <td align="left" id="mwsA">Mumbai</td>
 <td id="mwsQ">29.1</td>
 <td id="mwsg">5.5</td>
 <td id="mwsw">17.6</td>
 <td id="mwtA">166.5</td>
 <td align="left" id="mwtQ">Infotech</td></tr>,
 <tr id="mwtg">
 <td id="mwtw">13</td>
 <td id="mwuA">440</td>
 <td align="left" id="mwuQ"><a href="https://en.wikipedia.org/wiki/Bank_of_Baroda" id="mwug" rel="mw:WikiLink" title="Bank of Baroda">Bank of Baroda</a></td>
 <td align="left" id="mwuw">Vadodara</td>
 <td id="mwvA">17.1</td>
 <td id="mwvQ">2.3</td>
 <td id="mwvg">198.4</td>
 <td id="mwvw">16.2</td>
 <td align="left" id="mwwA">Banking</td></tr>,
 <tr id="mwwQ">
 <td id="mwwg">14</td>
 <td id="mwww">442</td>
 <td align="left" id="mwxA"><a href="https://en.wikipedia.org/wiki/Kotak_Mahindra_Bank" id="mwxQ" rel="mw:WikiLink" title="Kotak Mahindra Bank">Kotak Mahindra Bank</a></td>
 <td align="left" id="mwxg">Mumbai</td>
 <td id="mwxw">11.4</td>
 <td id="mwyA">2.2</td>
 <td id="mwyQ">92.0</td>
 <td id="mwyg">40.5</td>
 <td align="left" id="mwyw">Banking</td></tr>,
 <tr id="mwzA">
 <td id="mwzQ">15</td>
 <td id="mwzg">472</td>
 <td align="left" id="mwzw"><a href="https://en.wikipedia.org/wiki/Bharti_Airtel" id="mw0A" rel="mw:WikiLink" title="Bharti Airtel">Bharti Airtel</a></td>
 <td align="left" id="mw0Q">New Delhi</td>
 <td id="mw0g">18.1</td>
 <td id="mw0w">0.9</td>
 <td id="mw1A">53.3</td>
 <td id="mw1Q">91.5</td>
 <td align="left" id="mw1g">Telecommunication</td></tr>,
 <tr id="mw1w">
 <td id="mw2A">16</td>
 <td id="mw2Q">488</td>
 <td align="left" id="mw2g"><a href="https://en.wikipedia.org/wiki/Coal_India" id="mw2w" rel="mw:WikiLink" title="Coal India">Coal India</a></td>
 <td align="left" id="mw3A">Kolkata</td>
 <td id="mw3Q">17.2</td>
 <td id="mw3g">3.9</td>
 <td id="mw3w">28.5</td>
 <td id="mw4A">34.8</td>
 <td align="left" id="mw4Q">Metals and mining</td></tr>,
 <tr id="mw4g">
 <td id="mw4w">17</td>
 <td id="mw5A">525</td>
 <td align="left" id="mw5Q"><a href="https://en.wikipedia.org/wiki/Canara_Bank" id="mw5g" rel="mw:WikiLink" title="Canara Bank">Canara Bank</a></td>
 <td align="left" id="mw5w">Bangalore</td>
 <td id="mw6A">16.8</td>
 <td id="mw6Q">1.8</td>
 <td id="mw6g">184.0</td>
 <td id="mw6w">12.4</td>
 <td align="left" id="mw7A">Banking</td></tr>,
 <tr id="mw7Q">
 <td id="mw7g">18</td>
 <td id="mw7w">533</td>
 <td align="left" id="mw8A"><a href="https://en.wikipedia.org/wiki/Power_Finance_Corporation" id="mw8Q" rel="mw:WikiLink" title="Power Finance Corporation">Power Finance Corporation</a></td>
 <td align="left" id="mw8g">New Delhi</td>
 <td id="mw8w">11.1</td>
 <td id="mw9A">2.4</td>
 <td id="mw9Q">124.6</td>
 <td id="mw9g">18.5</td>
 <td align="left" id="mw9w">Financials</td></tr>,
 <tr id="mw-A">
 <td id="mw-Q">19</td>
 <td id="mw-g">537</td>
 <td align="left" id="mw-w"><a href="https://en.wikipedia.org/wiki/Bharat_Petroleum" id="mw_A" rel="mw:WikiLink" title="Bharat Petroleum">Bharat Petroleum</a></td>
 <td align="left" id="mw_Q">Mumbai</td>
 <td id="mw_g">54.1</td>
 <td id="mw_w">3.2</td>
 <td id="mwAQA">24.3</td>
 <td id="mwAQE">16.4</td>
 <td align="left" id="mwAQI">Oil and gas</td></tr>,
 <tr id="mwAQM">
 <td id="mwAQQ">20</td>
 <td id="mwAQU">569</td>
 <td align="left" id="mwAQY"><a href="https://en.wikipedia.org/wiki/Infosys" id="mwAQc" rel="mw:WikiLink" title="Infosys">Infosys</a></td>
 <td align="left" id="mwAQg">Bangalore</td>
 <td id="mwAQk">18.6</td>
 <td id="mwAQo">3.2</td>
 <td id="mwAQs">16.5</td>
 <td id="mwAQw">71.9</td>
 <td align="left" id="mwAQ0">Infotech</td></tr>,
 <tr id="mwAQ4">
 <td id="mwAQ8">21</td>
 <td id="mwARA">571</td>
 <td align="left" id="mwARE"><a href="https://en.wikipedia.org/wiki/Punjab_National_Bank" id="mwARI" rel="mw:WikiLink" title="Punjab National Bank">Punjab National Bank</a></td>
 <td align="left" id="mwARM">New Delhi</td>
 <td id="mwARQ">14.8</td>
 <td id="mwARU">1.1</td>
 <td id="mwARY">191.7</td>
 <td id="mwARc">16.5</td>
 <td align="left" id="mwARg">Banking</td></tr>,
 <tr id="mwARk">
 <td id="mwARo">22</td>
 <td id="mwARs">575</td>
 <td align="left" id="mwARw"><a href="https://en.wikipedia.org/wiki/Union_Bank_of_India" id="mwAR0" rel="mw:WikiLink" title="Union Bank of India">Union Bank of India</a></td>
 <td align="left" id="mwAR4">Mumbai</td>
 <td id="mwAR8">14.3</td>
 <td id="mwASA">1.7</td>
 <td id="mwASE">168.1</td>
 <td id="mwASI">12.7</td>
 <td align="left" id="mwASM">Banking</td></tr>,
 <tr id="mwASQ">
 <td id="mwASU">23</td>
 <td id="mwASY">592</td>
 <td align="left" id="mwASc"><a href="https://en.wikipedia.org/wiki/Bajaj_Finserv" id="mwASg" rel="mw:WikiLink" title="Bajaj Finserv">Bajaj Finserv</a></td>
 <td align="left" id="mwASk">Pune</td>
 <td id="mwASo">13.0</td>
 <td id="mwASs">1.0</td>
 <td id="mwASw">64.5</td>
 <td id="mwAS0">30.3</td>
 <td align="left" id="mwAS4">Financials</td></tr>,
 <tr id="mwAS8">
 <td id="mwATA">24</td>
 <td id="mwATE">593</td>
 <td align="left" id="mwATI"><a href="https://en.wikipedia.org/wiki/Mahindra_&amp;_Mahindra" id="mwATM" rel="mw:WikiLink" title="Mahindra &amp; Mahindra">Mahindra &amp; Mahindra</a></td>
 <td align="left" id="mwATQ">Mumbai</td>
 <td id="mwATU">16.8</td>
 <td id="mwATY">1.4</td>
 <td id="mwATc">28.3</td>
 <td id="mwATg">37.5</td>
 <td align="left" id="mwATk">Automotive</td></tr>,
 <tr id="mwATo">
 <td id="mwATs">25</td>
 <td id="mwATw">645</td>
 <td align="left" id="mwAT0"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/JSW_Steel_Ltd" id="mwAT4" rel="mw:WikiLink" title="JSW Steel Ltd">JSW Steel Ltd</a></td>
 <td align="left" id="mwAT8">Mumbai</td>
 <td id="mwAUA">21.1</td>
 <td id="mwAUE">1.1</td>
 <td id="mwAUI">27.4</td>
 <td id="mwAUM">26.6</td>
 <td align="left" id="mwAUQ">Iron and steel</td></tr>,
 <tr id="mwAUU">
 <td id="mwAUY">26</td>
 <td id="mwAUc">684</td>
 <td align="left" id="mwAUg"><a href="https://en.wikipedia.org/wiki/Hindalco_Industries" id="mwAUk" rel="mw:WikiLink" title="Hindalco Industries">Hindalco Industries</a></td>
 <td align="left" id="mwAUo">Mumbai</td>
 <td id="mwAUs">26.1</td>
 <td id="mwAUw">1.1</td>
 <td id="mwAU0">27.1</td>
 <td id="mwAU4">17.7</td>
 <td align="left" id="mwAU8">Metals and mining</td></tr>,
 <tr id="mwAVA">
 <td id="mwAVE">27</td>
 <td id="mwAVI">746</td>
 <td align="left" id="mwAVM"><a href="https://en.wikipedia.org/wiki/Grasim_Industries" id="mwAVQ" rel="mw:WikiLink" title="Grasim Industries">Grasim Industries</a></td>
 <td align="left" id="mwAVU">Mumbai</td>
 <td id="mwAVY">15.3</td>
 <td id="mwAVc">0.7</td>
 <td id="mwAVg">47.0</td>
 <td id="mwAVk">19.8</td>
 <td align="left" id="mwAVo">Diversified</td></tr>,
 <tr id="mwAVs">
 <td id="mwAVw">28</td>
 <td id="mwAV0">764</td>
 <td align="left" id="mwAV4"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/HCL_Technologies" id="mwAV8" rel="mw:WikiLink" title="HCL Technologies">HCL Technologies</a></td>
 <td align="left" id="mwAWA">Noida</td>
 <td id="mwAWE">13.3</td>
 <td id="mwAWI">1.9</td>
 <td id="mwAWM">12.0</td>
 <td id="mwAWQ">43.4</td>
 <td align="left" id="mwAWU">Infotech</td></tr>,
 <tr id="mwAWY">
 <td id="mwAWc">29</td>
 <td id="mwAWg">810</td>
 <td align="left" id="mwAWk"><a href="https://en.wikipedia.org/wiki/ITC_Limited" id="mwAWo" rel="mw:WikiLink" title="ITC Limited">ITC Limited</a></td>
 <td align="left" id="mwAWs">Kolkata</td>
 <td id="mwAWw">8.5</td>
 <td id="mwAW0">2.5</td>
 <td id="mwAW4">10.5</td>
 <td id="mwAW8">65.4</td>
 <td align="left" id="mwAXA">Consumer goods</td></tr>,
 <tr id="mwAXE">
 <td id="mwAXI">30</td>
 <td id="mwAXM">827</td>
 <td align="left" id="mwAXQ"><a href="https://en.wikipedia.org/wiki/Power_Grid_Corporation_of_India" id="mwAXU" rel="mw:WikiLink" title="Power Grid Corporation of India">Power Grid Corporation of India</a></td>
 <td align="left" id="mwAXY">Gurgaon</td>
 <td id="mwAXc">5.6</td>
 <td id="mwAXg">1.9</td>
 <td id="mwAXk">29.6</td>
 <td id="mwAXo">35.0</td>
 <td align="left" id="mwAXs">Utilities</td></tr>,
 <tr id="mwAXw">
 <td id="mwAX0">31</td>
 <td id="mwAX4">834</td>
 <td align="left" id="mwAX8"><a href="https://en.wikipedia.org/wiki/Tata_Steel" id="mwAYA" rel="mw:WikiLink" title="Tata Steel">Tata Steel</a></td>
 <td align="left" id="mwAYE">Kolkata</td>
 <td id="mwAYI">28.3</td>
 <td id="mwAYM">−0.4</td>
 <td id="mwAYQ">32.7</td>
 <td id="mwAYU">25.1</td>
 <td align="left" id="mwAYY">Iron and steel</td></tr>,
 <tr id="mwAYc">
 <td id="mwAYg">32</td>
 <td id="mwAYk">901</td>
 <td align="left" id="mwAYo"><a href="https://en.wikipedia.org/wiki/IndusInd_Bank" id="mwAYs" rel="mw:WikiLink" title="IndusInd Bank">IndusInd Bank</a></td>
 <td align="left" id="mwAYw">Mumbai</td>
 <td id="mwAY0">6.7</td>
 <td id="mwAY4">1.1</td>
 <td id="mwAY8">61.8</td>
 <td id="mwAZA">13.2</td>
 <td align="left" id="mwAZE">Banking</td></tr>,
 <tr id="mwAZI">
 <td id="mwAZM">33</td>
 <td id="mwAZQ">922</td>
 <td align="left" id="mwAZU"><a href="https://en.wikipedia.org/wiki/Indian_Railway_Finance_Corporation" id="mwAZY" rel="mw:WikiLink" title="Indian Railway Finance Corporation">Indian Railway Finance Corporation</a></td>
 <td align="left" id="mwAZc">New Delhi</td>
 <td id="mwAZg">3.2</td>
 <td id="mwAZk">0.7</td>
 <td id="mwAZo">58.6</td>
 <td id="mwAZs">26.5</td>
 <td align="left" id="mwAZw">Financials</td></tr>,
 <tr id="mwAZ0">
 <td id="mwAZ4">34</td>
 <td id="mwAZ8">926</td>
 <td align="left" id="mwAaA"><a href="https://en.wikipedia.org/wiki/Wipro" id="mwAaE" rel="mw:WikiLink" title="Wipro">Wipro</a></td>
 <td align="left" id="mwAaI">Bangalore</td>
 <td id="mwAaM">10.8</td>
 <td id="mwAaQ">1.3</td>
 <td id="mwAaU">13.8</td>
 <td id="mwAaY">28.9</td>
 <td align="left" id="mwAac">Infotech</td></tr>,
 <tr id="mwAag">
 <td id="mwAak">35</td>
 <td id="mwAao">930</td>
 <td align="left" id="mwAas"><a href="https://en.wikipedia.org/wiki/GAIL" id="mwAaw" rel="mw:WikiLink" title="GAIL">GAIL</a></td>
 <td align="left" id="mwAa0">New Delhi</td>
 <td id="mwAa4">16.1</td>
 <td id="mwAa8">1.2</td>
 <td id="mwAbA">15.0</td>
 <td id="mwAbE">16.1</td>
 <td align="left" id="mwAbI">Oil and gas</td></tr>,
 <tr id="mwAbM">
 <td id="mwAbQ">36</td>
 <td id="mwAbU">947</td>
 <td align="left" id="mwAbY"><a href="https://en.wikipedia.org/wiki/Indian_Bank" id="mwAbc" rel="mw:WikiLink" title="Indian Bank">Indian Bank</a></td>
 <td align="left" id="mwAbg">Chennai</td>
 <td id="mwAbk">7.8</td>
 <td id="mwAbo">1.0</td>
 <td id="mwAbs">95.4</td>
 <td id="mwAbw">8.7</td>
 <td align="left" id="mwAb0">Banking</td></tr>,
 <tr id="mwAb4">
 <td id="mwAb8">37</td>
 <td id="mwAcA">961</td>
 <td align="left" id="mwAcE"><a href="https://en.wikipedia.org/wiki/Vedanta_Limited" id="mwAcI" rel="mw:WikiLink" title="Vedanta Limited">Vedanta Limited</a></td>
 <td align="left" id="mwAcM">Mumbai</td>
 <td id="mwAcQ">17.4</td>
 <td id="mwAcU">0.5</td>
 <td id="mwAcY">22.9</td>
 <td id="mwAcc">19.7</td>
 <td align="left" id="mwAcg">Metals and mining</td></tr>,
 <tr id="mwAck">
 <td id="mwAco">38</td>
 <td id="mwAcs">1048</td>
 <td align="left" id="mwAcw"><a href="https://en.wikipedia.org/wiki/Adani_Power" id="mwAc0" rel="mw:WikiLink" title="Adani Power">Adani Power</a></td>
 <td align="left" id="mwAc4"><a href="https://en.wikipedia.org/wiki/Ahmedabad" id="mwAc8" rel="mw:WikiLink" title="Ahmedabad">Ahmedabad</a></td>
 <td id="mwAdA">6.1</td>
 <td id="mwAdE">2.5</td>
 <td id="mwAdI">11.1</td>
 <td id="mwAdM">29.4</td>
 <td align="left" id="mwAdQ"><a href="https://en.wikipedia.org/wiki/Energy" id="mwAdU" rel="mw:WikiLink" title="Energy">Energy</a></td></tr>,
 <tr id="mwAdY">
 <td id="mwAdc">39</td>
 <td id="mwAdg">1053</td>
 <td align="left" id="mwAdk"><a href="https://en.wikipedia.org/wiki/Bank_of_India" id="mwAdo" rel="mw:WikiLink" title="Bank of India">Bank of India</a></td>
 <td align="left" id="mwAds">Mumbai</td>
 <td id="mwAdw">8.1</td>
 <td id="mwAd0">0.8</td>
 <td id="mwAd4">110.8</td>
 <td id="mwAd8">6.7</td>
 <td align="left" id="mwAeA">Banking</td></tr>,
 <tr id="mwAeE">
 <td id="mwAeI">40</td>
 <td id="mwAeM">1059</td>
 <td align="left" id="mwAeQ"><a href="https://en.wikipedia.org/wiki/Adani_Enterprises" id="mwAeU" rel="mw:WikiLink" title="Adani Enterprises">Adani Enterprises</a></td>
 <td align="left" id="mwAeY">Ahmedabad</td>
 <td id="mwAec">12.7</td>
 <td id="mwAeg">0.4</td>
 <td id="mwAek">19.3</td>
 <td id="mwAeo">41.9</td>
 <td align="left" id="mwAes">Holding</td></tr>,
 <tr id="mwAew">
 <td id="mwAe0">41</td>
 <td id="mwAe4">1161</td>
 <td align="left" id="mwAe8"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Sun_Pharmaceutical" id="mwAfA" rel="mw:WikiLink" title="Sun Pharmaceutical">Sun Pharmaceutical</a></td>
 <td align="left" id="mwAfE">Mumbai</td>
 <td id="mwAfI">5.7</td>
 <td id="mwAfM">1.1</td>
 <td id="mwAfQ">9.6</td>
 <td id="mwAfU">44.1</td>
 <td align="left" id="mwAfY"><a href="https://en.wikipedia.org/wiki/Pharmaceutical_industry" id="mwAfc" rel="mw:WikiLink" title="Pharmaceutical industry">Pharmaceuticals</a></td></tr>,
 <tr id="mwAfg">
 <td id="mwAfk">42</td>
 <td id="mwAfo">1212</td>
 <td align="left" id="mwAfs"><a href="https://en.wikipedia.org/wiki/IndiGo" id="mwAfw" rel="mw:WikiLink" title="IndiGo">IndiGo</a></td>
 <td align="left" id="mwAf0">Gurgaon</td>
 <td id="mwAf4">7.9</td>
 <td id="mwAf8">0.9</td>
 <td id="mwAgA">8.8</td>
 <td id="mwAgE">20.2</td>
 <td align="left" id="mwAgI"><a href="https://en.wikipedia.org/wiki/Airline" id="mwAgM" rel="mw:WikiLink" title="Airline">Airline</a></td></tr>,
 <tr id="mwAgQ">
 <td id="mwAgU">43</td>
 <td id="mwAgY">1219</td>
 <td align="left" id="mwAgc"><a href="https://en.wikipedia.org/wiki/Adani_Ports_&amp;_SEZ" id="mwAgg" rel="mw:WikiLink" title="Adani Ports &amp; SEZ">Adani Ports &amp; SEZ</a></td>
 <td align="left" id="mwAgk">Ahmedabad</td>
 <td id="mwAgo">3.2</td>
 <td id="mwAgs">1.0</td>
 <td id="mwAgw">14.3</td>
 <td id="mwAg0">34.6</td>
 <td align="left" id="mwAg4"><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Shipping" id="mwAg8" rel="mw:WikiLink" title="Shipping">Shipping</a></td></tr>,
 <tr id="mwAhA">
 <td id="mwAhE">44</td>
 <td id="mwAhI">1259</td>
 <td align="left" id="mwAhM"><a href="https://en.wikipedia.org/wiki/IDBI_Bank" id="mwAhQ" rel="mw:WikiLink" title="IDBI Bank">IDBI Bank</a></td>
 <td align="left" id="mwAhU">Mumbai</td>
 <td id="mwAhY">3.7</td>
 <td id="mwAhc">0.7</td>
 <td id="mwAhg">43.7</td>
 <td id="mwAhk">10.9</td>

In [15]:
for row in column_data[1:]:
    row_data = row.find_all('td')
    individual_row_data = [data.text.strip() for data in row_data]

    length = len(df)
    df.loc[length] = individual_row_data

In [16]:

pd.set_option('display.max_rows', None)  # show all rows
df

,Rank,Forbes 2000 rank,Name,Headquarters,Revenue(billions US$),Profit(billions US$),Assets(billions US$),Value(billions US$),Industry
0,1,49,Reliance Industries Limited,Mumbai,108.8,8.4,210.5,233.1,Conglomerate
1,2,55,State Bank of India,Mumbai,71.8,8.1,807.4,87.6,Banking
2,3,65,HDFC Bank,Mumbai,49.3,7.7,483.2,133.6,Banking
3,4,70,Life Insurance Corporation,New Delhi,98.0,4.9,561.4,73.6,Insurance
4,5,142,ICICI Bank,Mumbai,28.5,5.3,283.5,95.3,Banking
5,6,207,Oil and Natural Gas Corporation,New Delhi,77.5,5.1,80.6,41.9,Oil and gas
6,7,259,Indian Oil Corporation,New Delhi,93.8,5.0,57.8,27.8,Oil and gas
7,8,284,Tata Motors,Mumbai,52.9,3.8,44.4,43.8,Automotive
8,9,293,Axis Bank,Mumbai,16.7,3.2,182.0,42.3,Banking
9,10,372,NTPC Limited,New Delhi,21.2,2.4,54.7,42.5,Utilities
10,11,398,Larsen & Toubro,Mumbai,26.7,1.6,40.7,56.9,Capital goods
11,12,412,Tata Consultancy Services,Mumbai,29.1,5.5,17.6,166.5,Infotech
12,13,440,Bank of Baroda,Vadodara,17.1,2.3,198.4,16.2,Banking
13,14,442,Kotak Mahindra Bank,Mumbai,11.4,2.2,92.0,40.5,Banking
14,15,472,Bharti Airtel,New Delhi,18.1,0.9,53.3,91.5,Telecommunication
15,16,488,Coal India,Kolkata,17.2,3.9,28.5,34.8,Metals and mining
16,17,525,Canara Bank,Bangalore,16.8,1.8,184.0,12.4,Banking
17,18,533,Power Finance Corporation,New Delhi,11.1,2.4,124.6,18.5,Financials
18,19,537,Bharat Petroleum,Mumbai,54.1,3.2,24.3,16.4,Oil and gas
19,20,569,Infosys,Bangalore,18.6,3.2,16.5,71.9,Infotech
20,21,571,Punjab National Bank,New Delhi,14.8,1.1,191.7,16.5,Banking
21,22,575,Union Bank of India,Mumbai,14.3,1.7,168.1,12.7,Banking
22,23,592,Bajaj Finserv,Pune,13.0,1.0,64.5,30.3,Financials
23,24,593,Mahindra & Mahindra,Mumbai,16.8,1.4,28.3,37.5,Automotive
24,25,645,JSW Steel Ltd,Mumbai,21.1,1.1,27.4,26.6,Iron and steel
25,26,684,Hindalco Industries,Mumbai,26.1,1.1,27.1,17.7,Metals and mining
26,27,746,Grasim Industries,Mumbai,15.3,0.7,47.0,19.8,Diversified
27,28,764,HCL Technologies,Noida,13.3,1.9,12.0,43.4,Infotech
28,29,810,ITC Limited,Kolkata,8.5,2.5,10.5,65.4,Consumer goods
29,30,827,Power Grid Corporation of India,Gurgaon,5.6,1.9,29.6,35.0,Utilities
30,31,834,Tata Steel,Kolkata,28.3,−0.4,32.7,25.1,Iron and steel
31,32,901,IndusInd Bank,Mumbai,6.7,1.1,61.8,13.2,Banking
32,33,922,Indian Railway Finance Corporation,New Delhi,3.2,0.7,58.6,26.5,Financials
33,34,926,Wipro,Bangalore,10.8,1.3,13.8,28.9,Infotech
34,35,930,GAIL,New Delhi,16.1,1.2,15.0,16.1,Oil and gas
35,36,947,Indian Bank,Chennai,7.8,1.0,95.4,8.7,Banking
36,37,961,Vedanta Limited,Mumbai,17.4,0.5,22.9,19.7,Metals and mining
37,38,1048,Adani Power,Ahmedabad,6.1,2.5,11.1,29.4,Energy
38,39,1053,Bank of India,Mumbai,8.1,0.8,110.8,6.7,Banking
39,40,1059,Adani Enterprises,Ahmedabad,12.7,0.4,19.3,41.9,Holding
40,41,1161,Sun Pharmaceutical,Mumbai,5.7,1.1,9.6,44.1,Pharmaceuticals
41,42,1212,IndiGo,Gurgaon,7.9,0.9,8.8,20.2,Airline
42,43,1219,Adani Ports & SEZ,Ahmedabad,3.2,1.0,14.3,34.6,Shipping
43,44,1259,IDBI Bank,Mumbai,3.7,0.7,43.7,10.9,Banking
44,45,1264,Bajaj Auto,Pune,5.4,0.9,4.7,29.4,Automotive
45,46,1281,Shriram Transport Finance,Chennai,4.4,0.9,29.8,10.7,Financials
46,47,1384,Asian Paints,Mumbai,4.3,0.7,3.6,32.3,Chemicals
47,48,1534,Tata Power,Mumbai,7.4,0.5,16.7,16.7,Utilities
48,49,1562,Titan Company,Bangalore,6.2,0.0,2.3,1.1,Gems and jewellery
49,50,1604,Jio Financial Services,Mumbai,0.2,0.2,17.4,27.2,Financials
50,49,1568,Rajesh Exports,Bangalore,32.6,0.1,4.1,2.0,Gems and jewellery
51,50,1617,DMart,Mumbai,6.1,0.3,2.5,36.6,Retail
52,51,1693,Jindal Steel and Power,New Delhi,6.0,0.6,9.4,12.4,Iron and steel
53,52,1697,LIC Housing Finance,Mumbai,3.3,0.4,34.9,4.3,Financials
54,53,1699,Adani Green Energy,Ahmedabad,1.1,0.1,10.6,34.8,Renewable energy
55,54,1704,Bajaj Holdings & Investment,Mumbai,0.2,0.9,7.8,11.0,Holding
56,55,1760,General Insurance Corporation,Mumbai,5.7,0.9,20.9,7.2,Insurance
57,56,1769,Yes Bank,Mumbai,4.0,0.2,48.7,8.3,Banking
58,57,1805,Motherson Sumi Systems,Noida,11.4,0.2,9.4,10.5,Automotive
59,58,1821,Bharat Electronics,Bangalore,2.2,0.4,4.4,21.8,Aerospace and defense
60,59,1840,Central Bank of India,Mumbai,4.3,0.3,53.7,6.4,Banking
61,60,1842,Bank of Maharashtra,Pune,2.8,0.5,36.8,5.5,Banking
62,61,1848,Indus Towers,Gurgaon,3.5,0.7,6.7,11.1,Telecommunication
63,62,1853,Steel Authority of India,New Delhi,12.9,0.4,15.6,8.3,Iron and steel
64,63,1869,Federal Bank,Kochi,3.2,0.5,38.1,4.8,Banking
65,64,1873,DLF,Gurgaon,0.8,0.3,7.2,25.2,Real estate
66,65,1895,Dr. Reddy's Laboratories,Hyderabad,3.4,0.7,4.6,11.6,Pharmaceuticals
67,66,1908,Varun Beverages,Gurgaon,2.0,0.3,1.8,23.6,Beverages
68,67,1949,CIFCL,Chennai,2.3,0.4,18.8,13.0,Financials
69,68,1957,NMDC,Hyderabad,2.5,0.8,3.9,9.7,Mining
70,69,1980,ABB India,Bangalore,1.3,0.2,1.3,21.3,Capital goods

In [17]:
df.to_csv(r"C:\Users\DELL\Videos\anacondabin\bywebscraping.csv", index = False)